<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>xcoinpay</title>
    <meta name="keywords" content="FomoXYT官网，FomoXYT，预约活动，区块链">
    <meta name="description" content="FomoXYT，区块链，交易所，虚拟币交易">
    <link rel="shortcut icon" href="/public/images/xcoinpay.ico">
    <link rel="stylesheet" href="/public/css/index/main.css">
    <link rel="stylesheet" href="/public/css/index/olduser.css">
</head>
<body>
    <div class="box">
        <!--  head  -->
        <?php load_view("inc/pc_nav");?>
        <!--  个人中心导航  -->
        <?php load_view("inc/user_left");?>

        <!--  老用户钱包与理财信息  -->
        <div class="olduser-box">
            <div class="warp-1200">
                <div class="per-title"><span class="p-online"></span><span class="p-text">我的理财</span><p class="fr pr more-box" onclick="window.location.href='/user/transaction?type=olduser'"><span class="more-text">查看交易记录</span><span class="p-more"></span></p></div>
                <table class="reference">
                    <tbody>
                    <tr>                                  　
                        <th>总额（XYT）</th>
                        <th>累计收益（XYT）</th>
                        <th>可提币（XYT）</th>
                        <th>操作</th>
                    </tr>
                    <tr>
                        <td title="暂无数据"><?=$userinfo['xyt_num']?></td>
                        <td title="暂无数据">暂无数据</td>
                        <td title="暂无数据"><?=$userinfo['xyt_available_balance']?></td>
                        <td title="暂无数据">暂无数据</td>
                    </tr>

<!--                    <tr>-->
<!--                        <td title="201800.000">201800.000</td>-->
<!--                        <td title="180.0000000">180.0000000</td>-->
<!--                        <td title="201800.000">201800.000</td>-->
<!--                        <td><a class="embody" href="javascript:void(0);">提币</a></td>-->
<!--                    </tr>-->

                    </tbody>
                </table>
            </div>
            <div class="warp-1200">
                <div class="per-title"><span class="p-online"></span><span class="p-text">我的钱包订单</span></div>
                <table class="reference money-order">
                    <tbody>
                    <tr>                                  　　
                        <th>订单号</th>
                        <th>创建时间</th>
                        <th>披萨钱包数量</th>
                        <th>赠送XYT代币数量</th>
                        <th>颜色</th>
                        <th>状态</th>
                    </tr>
                    <?php if(!empty($shop)): ?>
                        <?php foreach($shop as $k=>$v): ?>
                        <tr>
                            <td title="<?=$v['id']?>"><?=$v['id']?></td>
                            <td title="<?=$v['ctime']?>"><?=$v['ctime']?></td>
                            <td title="<?=$v['wallet_number']?>"><?=$v['wallet_number']?></td>
                            <td title="<?=$v['xyt_number']?>"><?=$v['xyt_number']?></td>
                            <?php
                            if($v['color_type'] == 1){
                                $color = "经典黑";
                            }else if($v['color_type'] == 2){
                                $color = "成功银";
                            }else{
                                $color = "土豪金";
                            }
                            ?>
                            <td title="<?=$color?>"><?=$color?></td>
                            <td title="<?=$v['is_receive']==1?"已发货":"待付款"?>"><span style="color: #ef2727;"><?=$v['is_receive']==1?"已发货":"待付款"?></span></td>
                        </tr>
                        <?php endforeach; ?>
                    <?php else: ?>
                        <tr>
                            <td title="暂无数据">暂无数据</td>
                            <td title="暂无数据">暂无数据</td>
                            <td title="暂无数据">暂无数据</td>
                            <td title="暂无数据">暂无数据</td>
                            <td title="暂无数据">暂无数据</td>
                            <td title="暂无数据">暂无数据</td>
                        </tr>
                    <?php endif; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</body>
</html>