<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>xcoinpay</title>
    <meta name="keywords" content="FomoXYT官网，FomoXYT，预约活动，区块链">
    <meta name="description" content="FomoXYT，区块链，交易所，虚拟币交易">
    <link rel="shortcut icon" href="/public/images/xcoinpay.ico">
    <link rel="stylesheet" href="/public/css/index/main.css">
    <link rel="stylesheet" href="/public/css/index/partnerslogin.css">
</head>
<body>


    <!--  先登录，登录成功后再显示内容  -->
    <div class="popup-box">
        <div class="popup-title"><span>请输入密码</span></div>
        <div class="popup-body">
            <div class="p-pwd-box"><input type="password" placeholder="请输入密码"></div>
            <div class="r-foot address-f ov">
                <div class="fr">
                    <a class="call-btn" href="javascript:history.back(-1);">取消</a>
                    <a class="withdraw-btn" href="index/partners">确认</a>
                </div>
            </div>
        </div>
    </div>
</body>
</html>