<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>xcoinpay</title>
    <meta name="keywords" content="FomoXYT官网，FomoXYT，预约活动，区块链">
    <meta name="description" content="FomoXYT，区块链，交易所，虚拟币交易">
    <link rel="shortcut icon" href="/public/images/xcoinpay.ico">
    <link rel="stylesheet" href="/public/css/index/main.css">
    <link rel="stylesheet" href="/public/css/index/transaction.css">
</head>
<body>
    <div class="box">
        <!--  head  -->
        <?php load_view("inc/pc_nav");?>
        <!--  个人中心导航  -->
        <?php load_view("inc/user_left");?>

        <!--  nav  -->
        <div class="transaction-box">
            <div class="warp-1200">
                <ul class="ov tran-ul">
                    <li class="fl tran-active">定存记录</li>
                    <li class="fl">财务记录</li>
                    <li class="fl">提现记录</li>
                </ul>
                <div class="tran-b">
                    <!--  定存记录  -->
                    <div class="record-box t-active">
                        <table class="reference">
                            <tbody>
                            <tr>                                  　　
                                <th>订单号</th>
                                <th>定存期限（月）</th>
                                <th>到账日期</th>
                                <th>到账时间</th>
                                <th>数量</th>
                                <th>状态</th>
                            </tr>

                            <tr>
                                <td title="暂无数据">暂无数据</td>
                                <td title="暂无数据">暂无数据</td>
                                <td title="暂无数据">暂无数据</td>
                                <td title="暂无数据">暂无数据</td>
                                <td title="暂无数据">暂无数据</td>
                                <td title="暂无数据">暂无数据</td>
                            </tr>

<!--                            <tr>-->
<!--                                <td title="5007">5007</td>-->
<!--                                <td title="3">3</td>-->
<!--                                <td title="2019-08-26 16:37:49">2019-08-26 16:37:49</td>-->
<!--                                <td title="2019-08-26 16:37:49">2019-08-26 16:37:49</td>-->
<!--                                <td title="1000.000">1000.000</td>-->
<!--                                <td><span style="color: #ef2727;">待充值</span></td>-->
<!--                            </tr>-->

                            </tbody>
                        </table>
                    </div>
                    <!--  财务记录  -->
                    <div class="record-box">
                        <table class="reference">
                            <tbody>
                            <tr>                                  　　
                                <th>订单号</th>
                                <th>定存期限（月）</th>
                                <th>到账日期</th>
                                <th>到账时间</th>
                                <th>数量</th>
                                <th>状态</th>
                            </tr>
                            <tr>
                                <td title="暂无数据">暂无数据</td>
                                <td title="暂无数据">暂无数据</td>
                                <td title="暂无数据">暂无数据</td>
                                <td title="暂无数据">暂无数据</td>
                                <td title="暂无数据">暂无数据</td>
                                <td title="暂无数据">暂无数据</td>
                            </tr>
<!--                            <tr>-->
<!--                                <td title="5007">5007</td>-->
<!--                                <td title="3">3</td>-->
<!--                                <td title="2019-08-26 16:37:49">2019-08-26 16:37:49</td>-->
<!--                                <td title="2019-08-26 16:37:49">2019-08-26 16:37:49</td>-->
<!--                                <td title="1000.000">1000.000</td>-->
<!--                                <td><span style="color: #ef2727;">已过期</span></td>-->
<!--                            </tr>-->

                            </tbody>
                        </table>
                    </div>
                    <!--  提现记录  -->
                    <div class="record-box">
                        <table class="reference">
                            <tbody>
                            <tr>                                  　　
                                <th>提现订单号</th>
                                <th>创建时间</th>
                                <th>XYT以太坊地址</th>
                                <th>区块交易号</th>
                                <th>提币类型</th>
                                <th>提币状态</th>
                            </tr>
                            <tr>
                                <td title="暂无数据">暂无数据</td>
                                <td title="暂无数据">暂无数据</td>
                                <td title="暂无数据">暂无数据</td>
                                <td title="暂无数据">暂无数据</td>
                                <td title="暂无数据">暂无数据</td>
                                <td title="暂无数据">暂无数据</td>
                            </tr>
<!--                            <tr>-->
<!--                                <td title="1">1</td>-->
<!--                                <td title="2019-08-26 16:37:49">2019-08-26 16:37:49</td>-->
<!--                                <td title="0x0121245152451241541215415451245121254">0x0121245152451241541215415451245121254</td>-->
<!--                                <td title="0x0454asdsd545415454asd545a4sd54512125">0x0454asdsd545415454asd545a4sd54512125</td>-->
<!--                                <td title="订单提币">订单提币</td>-->
<!--                                <td><span style="color: #ef2727;">提币成功</span></td>-->
<!--                            </tr>-->
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script type="text/javascript" src="/public/js/jquery.min.js"></script>
    <script>
        $(function (){
            $(".tran-ul li").click(function (){
                //获取点击的元素给其添加样式，讲其兄弟元素的样式移除
                $(this).addClass("tran-active").siblings().removeClass("tran-active");
                //获取选中元素的下标
                var index = $(this).index();
                $(".record-box").eq(index).addClass("t-active").siblings().removeClass("t-active");
            });
        });
    </script>
</body>
</html>