<div class="left-nav">
    <div id="side-nav">
        <ul id="nav">
            <li>
                <a href="javascript:;"><i class="iconfont left-nav-li">&#xe726;</i><cite>用户管理</cite><i class="iconfont nav_right">&#xe697;</i></a>
                <ul class="sub-menu">
                    <li><a onclick="xadmin.add_tab('数据统计','/admin/stat')"><cite>数据统计</cite></a></li>
                    <li><a onclick="xadmin.add_tab('用户列表','/admin/userlist')"><cite>用户列表</cite></a></li>
                    <li><a onclick="xadmin.add_tab('充值记录','/admin/recharge')"><cite>充值记录</cite></a></li>
                    <li><a onclick="xadmin.add_tab('提现记录','/admin/withdraw')"><cite>提现记录</cite></a></li>
                    <li><a onclick="xadmin.add_tab('DXY霸屏会员列表','/admin/dyxpauserlist')"><cite>DXY霸屏会员列表</cite></a></li>
<!--                    <li><a onclick="xadmin.add_tab('DXY霸屏任务审核通过','/admin/dyxsuccess')"><cite>DXY霸屏任务审核通过</cite></a></li>-->
                    <li><a onclick="xadmin.add_tab('DXY新霸屏任务审核通过','/admin/dyxsuccess2')"><cite>DXY新霸屏任务审核通过</cite></a></li>
                    <li><a onclick="xadmin.add_tab('DXY拼多多预约记录','/admin/dyxdiscountlist')"><cite>DXY拼多多预约记录</cite></a></li>
                </ul>
            </li>
            <li>
                <a href="javascript:;"><i class="iconfont left-nav-li">&#xe699;</i><cite>排名管理</cite><i class="iconfont nav_right">&#xe697;</i></a>
                <ul class="sub-menu">
                    <li><a onclick="xadmin.add_tab('排名额度分配','/admin/bulidranking')"><cite>排名额度分配</cite></a></li>
                    <li><a onclick="xadmin.add_tab('个人排名','/admin/personalranking')"><cite>个人排名</cite></a></li>
                    <li><a onclick="xadmin.add_tab('团体排名','/admin/teamranking')"><cite>团体排名</cite></a></li>
                </ul>
            </li>
            <li>
                <a href="javascript:;"><i class="iconfont left-nav-li">&#xe761;</i><cite>活动管理</cite><i class="iconfont nav_right">&#xe697;</i></a>
                <ul class="sub-menu">
                    <li><a onclick="xadmin.add_tab('DXY群主额度福利','/admin/dyxdiscount')"><cite>DXY群主额度福利</cite></a></li>
<!--                    <li><a onclick="xadmin.add_tab('DXY霸屏任务发布','/admin/dyxrelease')"><cite>DXY霸屏任务发布</cite></a></li>-->
                    <li><a onclick="xadmin.add_tab('DYX拼多多活动列表','/admin/discount')"><cite>DYX拼多多活动列表</cite></a></li>
                    <li><a onclick="xadmin.add_tab('FOMO拍卖活动','/admin/auction')"><cite>FOMO拍卖活动</cite></a></li>
                </ul>
            </li>
            <li>
                <a href="javascript:;"><i class="iconfont left-nav-li">&#xe749;</i><cite>审核管理</cite><i class="iconfont nav_right">&#xe697;</i></a>
                <ul class="sub-menu">
                    <!--<li><a onclick="xadmin.add_tab('DXY霸屏会员申请','/admin/dyxpauser')"><cite>DXY霸屏会员申请</cite></a></li>-->
<!--                    <li><a onclick="xadmin.add_tab('DXY霸屏任务审核','/admin/dyxcheck')"><cite>DXY霸屏任务审核</cite></a></li>-->
                    <li><a onclick="xadmin.add_tab('DXY新霸屏任务审核','/admin/dyxcheck2')"><cite>DXY新霸屏任务审核</cite></a></li>
                    <li><a onclick="xadmin.add_tab('DXY新群主额度审核','/admin/dyxgroup')"><cite>DXY新群主额度审核</cite></a></li>
                </ul>
            </li>
            <li>
                <a href="javascript:;"><i class="iconfont left-nav-li">&#xe6ae;</i><cite>系统管理</cite><i class="iconfont nav_right">&#xe697;</i></a>
                <ul class="sub-menu">
                    <li><a onclick="xadmin.add_tab('系统管理员','/admin/system')"><cite>系统管理员</cite></a></li>
                    <li><a onclick="xadmin.add_tab('管理员日志','/admin/systemlog')"><cite>管理员日志</cite></a></li>
                    <li><a onclick="xadmin.add_tab('用户日志','/admin/userlog')"><cite>用户日志</cite></a></li>
                </ul>
            </li>
        </ul>
    </div>
</div>