<div class="left-nav">
    <div id="side-nav">
        <ul id="nav">
            <li>
                <a href="javascript:;"><i class="iconfont left-nav-li">&#xe726;</i><cite>DXY霸屏活动管理</cite><i class="iconfont nav_right">&#xe697;</i></a>
                <ul class="sub-menu">
<!--                    <li><a onclick="xadmin.add_tab('DXY霸屏任务发布','/operate/dyxrelease')"><cite>DXY霸屏任务发布</cite></a></li>-->
                    <li><a onclick="xadmin.add_tab('DXY霸屏会员列表','/operate/dyxpauserlist')"><cite>DXY霸屏会员列表</cite></a></li>
<!--                    <li><a onclick="xadmin.add_tab('DXY霸屏任务审核通过','/operate/dyxsuccess')"><cite>DXY霸屏任务审核通过</cite></a></li>-->
                    <li><a onclick="xadmin.add_tab('DXY新霸屏任务审核通过','/operate/dyxsuccess2')"><cite>DXY新霸屏任务审核通过</cite></a></li>
                    <li><a onclick="xadmin.add_tab('DXY新霸屏任务未通过','/operate/dyxerror')"><cite>DXY新霸屏任务未通过</cite></a></li>
                </ul>
            </li>
            <li>
                <a href="javascript:;"><i class="iconfont left-nav-li">&#xe749;</i><cite>奖励管理</cite><i class="iconfont nav_right">&#xe697;</i></a>
                <ul class="sub-menu">
                    <li><a onclick="xadmin.add_tab('DXY霸屏会员空投奖励','/operate/dyxkontou')"><cite>DXY霸屏会员空投奖励</cite></a></li>
                </ul>
            </li>
            <li>
                <a href="javascript:;"><i class="iconfont left-nav-li">&#xe749;</i><cite>审核管理</cite><i class="iconfont nav_right">&#xe697;</i></a>
                <ul class="sub-menu">
                    <li><a onclick="xadmin.add_tab('DXY霸屏会员申请','/operate/dyxpauser')"><cite>DXY霸屏会员申请</cite></a></li>
<!--                    <li><a onclick="xadmin.add_tab('DXY霸屏任务审核','/operate/dyxcheck')"><cite>DXY霸屏任务审核</cite></a></li>-->
                    <li><a onclick="xadmin.add_tab('DXY新霸屏任务审核','/operate/dyxcheck2')"><cite>DXY新霸屏任务审核</cite></a></li>
                </ul>
            </li>
            <li>
                <a href="javascript:;"><i class="iconfont left-nav-li">&#xe761;</i><cite>DYX群主额度管理</cite><i class="iconfont nav_right">&#xe697;</i></a>
                <ul class="sub-menu">
                    <li><a onclick="xadmin.add_tab('DXY群主额度福利','/operate/dyxdiscount')"><cite>DXY群主额度福利</cite></a></li>
                    <li><a onclick="xadmin.add_tab('DXY新群主额度审核','/operate/dyxgroup')"><cite>DXY新群主额度审核</cite></a></li>
                    <li><a onclick="xadmin.add_tab('DXY群主额度未通过','/operate/dyxgrouperror')"><cite>DXY群主额度未通过</cite></a></li>
                </ul>
            </li>
        </ul>
    </div>
</div>