<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="full-screen" content="yes">
    <title>xcoinpay</title>
    <meta name="keywords" content="XCoinPay官网，XCoinPay区块链，区块链XCoinPay柔支付，区块链柔支付，柔支付，FomoXYT官网，FomoXYT，预约活动，区块链">
    <meta name="description" content="XCoinPay，XCoinPay，区块链，交易所，虚拟币交易">
    <link rel="shortcut icon" href="/public/images/xcoinpay.ico">
    <link rel="stylesheet" href="/public/css/index/main.css">
    <link rel="stylesheet" href="/public/css/website/index.css">
</head>
<body>
    <div class="box">
        <!--  公共头部  -->
        <?php load_view("inc/pc_nav");?>

        <!--  回顾历史 预知未来  -->
        <div class="review-box">
            <div class="sale-box warp-1200">
                <p><i class="review-text"></i></p>
                <p><i class="decentralization-text"></i></p>
                <div class="xc-title">
                    <p>XCoinPay致力于打造加密数字货币行业的PayPal，XCoinPay专注于区块链支付方</p>
                    <p>向，产品布局涵盖有钱包、支付系统和区块链商业解决方案平台</p>
                </div>
                <ul class="ov xc-ul">
                    <li class="fl" id="patent-btn"><img src="/public/images/website/patent-icon.png" width="66" height="77" alt=""><p>专利</p></li>
                    <li class="fl" onclick="window.open('/public/file/DYX-bps2.6.pdf')"><img src="/public/images/website/wpaper-icon.png" width="57" height="70" alt=""><p>白皮书</p></li>
                    <li class="fl" onclick="window.open('/public/file/prize.pdf')"><img src="/public/images/website/reward-icon.png" width="58" height="70" alt=""><p>奖项</p></li>
                </ul>
            </div>
        </div>

        <!--  柔支付网络  -->
        <div class="warp-1220 pay-box">
            <p class="pay-network">柔支付网络</p>
            <div class="pay-introduce">
                <p>柔支付网络（RouPay Network）—— 一个瞬间、自由、安全的分布式链下支付网络</p>
                <p>未来将会有超过数十亿美金的token在柔支付网络（RouPay Network）上流动</p>
                <p>让我们掀起一场价值网络革命，让我们一起拥抱变革</p>
            </div>
            <ul class="ov pay-network-ul">
                <li class="fl"><img src="/public/images/website/currency-icon.png" width="66" height="66" alt=""><p class="ul-p">通用</p><p class="li-p">区块链支付行业的基础设施</p></li>
                <li class="fl"><img src="/public/images/website/security-icon.png" width="66" height="66" alt=""><p class="ul-p">安全</p><p class="li-p">去中心化保管用户资产、 绝对安全</p></li>
                <li class="fl"><img src="/public/images/website/concurrency-icon.png" width="66" height="66" alt=""><p class="ul-p">高并发</p><p class="li-p">柔支付网络使用链下清算的方式实现高并发</p></li>
                <li class="fl"><img src="/public/images/website/speed-icon.png" width="66" height="66" alt=""><p class="ul-p">极速且零手续费</p><p class="li-p">转账可以实现秒速到账且零手续费!在落地性和实用性方面远超闪电网络</p></li>
                <li class="fl"><img src="/public/images/website/expand-icon.png" width="66" height="66" alt=""><p class="ul-p">扩展性强</p><p class="li-p">作为一个区块链支付底层平台，可以衍生出诸多的商业方案，具有极大的拓展性和可编程性</p></li>
            </ul>
        </div>

        <!--  XCoinPay开放平台（商家版）  -->
        <div class="warp-1200 open-business">
            <div class="ov open-up">
                <div class="fl open-up-box">
                    <p class="open-up-text">XCoinPay开放平台（商家版）</p>
                    <p class="programme">提供多种基于柔支付网络开发的区块链支付解决方案</p>
                    <div class="pro-box">
                        <div class="ov pro-div"><i class="exchang-icon fl"></i><div class="fl solve-box"><p>交易所解决方案</p><span>接入柔支付网络的交易所，用户充值、提现都秒速到账且零手续费，带来极高的流动性</span></div></div>
                        <div class="ov pro-div"><i class="merchant-icon fl"></i><div class="fl solve-box"><p>商户解决方案</p><span>面对接受加密数字货币的购物平台的区块链支付解决方案</span></div></div>
                        <div class="ov pro-div"><i class="otc-icon fl"></i><div class="fl solve-box"><p>OTC解决方案</p><span>场外交易解决方案</span></div></div>
                    </div>
                </div>
                <div class="fl case-box">
                    <div class="otc-box wal-box"><img src="/public/images/website/OTC-img.png" width="154" height="170" alt=""><p>场外交易解决方案</p></div>
                    <div class="mer-box wal-box"><img src="/public/images/website/mer-img.png" width="240" height="129" alt=""><p>面对接受加密数字货币的购物平台的区块链支付解决方案</p></div>
                    <div class="exc-box wal-box"><img src="/public/images/website/exc-img.png" width="171" height="171" alt=""><p>接入柔支付网络的交易所，用户充值、提现都秒速到账且零手续费，带来极高的流动性</p></div>
                </div>
            </div>
        </div>

        <!--  XCoinPay手机钱包——区块链世界的选择  -->
        <div class="warp-1200 wallet-roupay-box">
            <div class="ov">
                <div class="fl w-rou-box">
                    <div class="wallet-box wal-box"><img src="/public/images/website/wallet-img.png" width="147" height="150" alt=""><p>可以链接硬件钱包</p></div>
                    <div class="roupay-box wal-box"><img src="/public/images/website/roupay-img.png" width="135" height="150" alt=""><p>柔支付网络</p></div>
                </div>
                <div class="fl wallet-art-box">
                    <p class="wallet-art-text">XCoinPay手机钱包——区块链世界的选择</p>
                    <div class="wallet-art">
                        <div class="ov wallet-art1"><p>可以链接硬件钱包</p><p>XCoinPay手机钱包可以链接披萨硬件钱包，披萨硬件钱包是XCoinPay团队荣誉出品的最安全易用的硬件钱包。</p></div>
                        <div class="ov wallet-art2"><p>柔支付网络</p><p>一个瞬间、自由、安全的通用分布式链下支付网络，区块链支付行业的基础设施。</p></div>
                    </div>
                </div>
            </div>
        </div>

        <!--  钱包类产品对比  -->
        <div class="wallet-product">
            <div class="warp-1200">
                <p>钱包类产品对比</p>
                <img src="/public/images/website/wallet-product-img.png" width="1275" height="681" alt="">
            </div>
        </div>

        <!--  团队与顾问  -->
        <div class="team-box">
            <div class="warp-1200 pr">
                <p class="team-t">团队与顾问</p>
                <p class="team-b">XCoinPay团队目前拥有彩色区块链技术专利与数个软件著作版权，XCoinPay团队的核心成员均来自于区块链业内，拥有深厚的业内资源及背景。</p>
                <div class="head-img-box">
                    <ul class="ov">
                        <li class="fl head-img h-active1"><p>顾问 - 周朝晖</p></li>
                        <li class="fl head-img h-active2"><p>CTO - 马龙</p></li>
                        <li class="fl head-img h-active3"><p>CEO - 赵世达</p></li>
                        <li class="fl head-img h-active4"><p>技术顾问 - 黄连金</p></li>
                    </ul>
                </div>
                <div class="head-introduce">
                    <div class="intro intro1">复旦大学毕业，中国狗狗币协会副会长、DACA协会与清华大学iCenter特聘讲师、世界区块链基金会（WBD）研究员、施比爱（shibe.io）创始人、Joomla开源建站系统资深协作者和专业咨询师。2003年起参与国际开源软件的协作，深谙开源项目和去中心化自治组织的运作机理。目前正在深入区块链的应用。<span class="triangle"></span></div>
                    <div class="intro intro2">武汉大学硕士，清华大学iCenter特聘讲师，亚洲区块链DACA协会特聘讲师，巴比特资讯专栏作家，巴比特意见领袖，IDGUI导航平台，8Doge币应用创始人，施比爱CTO&联合创始人，论坛版主。知名的作品有：脑口令钱包工具，新币产量减半倒计时，币域名平台，EW留言，彩色区块链等。<span class="triangle"></span></div>
                    <div class="intro intro3 i-active">资深互联网从业者，持有申报软件著作权两项，设计、运营过一系列互联网产品，产品涵盖有手机APP、自媒体网站、电商平台等，对区块链、数字货币发展密切关注，积极探索区块链落地应用。由于区块链的技术启发，设计过基于哈希算法、不可作弊的彩票抽奖系统。<span class="triangle"></span></div>
                    <div class="intro intro4">著名区块链专家 美国ACM Practitioner Board委员 Well-known Blockchain Expert ACM Practitioner Board Commit Member Chinese Electric Academy Blochchain Expert Committee Member<span class="triangle"></span></div>
                </div>
            </div>
        </div>

        <!--  订阅  -->
        <div class="subscribe">
            <div class="warp-1200 sub-be pr">
                <div class="su-box ov">
                    <div class="fl">
                        <p class="dynamic">输入您的邮箱，订阅我们的动态</p>
                        <div class="ov mailbox">
                            <input type="text" name="email" class="fl" placeholder="您的邮箱地址">
                            <button type="button" onclick="postComment()">订阅</button>
                        </div>
                    </div>
                    <div class="fl">
                        <p class="s-info1">订阅我们的周报和动态，重要信息会实时提醒</p>
                        <p class="s-info2">不错过任何重大信息</p>
                    </div>
                </div>
            </div>
        </div>

        <!--  问题解答  -->
        <div class="question">
            <div class="warp-1200 question-w">
                <div class="question-p">
                    <p class="question-t">FAQ</p>
                    <ul class="question-ul" id="q-ul">


                    </ul>
                </div>
            </div>
        </div>


        <!--  尾部  -->
        <div class="footer">
            <div class="warp-1200 ov">
                <p class="fl logo-big"><img src="/public/images/website/logo-big.png" width="166" height="141" alt=""></p>
                <!--<div class="fl account-num">
                    <p class="official">官网账号</p>
                    <p class="account1"><i class="telegram"></i>Telegram</p>
                    <p class="account1"><i class="twitter"></i>Twitter</p>
                    <p class="account1"><i class="facebook"></i>Facebook</p>
                    <p class="account1"><i class="microblog"></i>Microblog</p>
                </div>-->
                <div class="fl account-num">
                    <p class="official">关注我们</p>
                    <div class="ov qrcode-box">
                        <div class="fl qrcode1"><img src="/public/images/website/public-number.png" width="860" height="860" alt=""><p>扫码关注微信公众号 </p></div>
                        <div class="fl qrcode2"><img src="/public/images/website/official-group.png" width="445" height="440" alt="" class="official-group"><p>扫码进官方群 </p></div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="popup">
        <div class="popup-title"><i class="cancel"></i></div>
        <div class="popup-body">
            <p><a href="/public/file/administration.pdf" target="_blank">1、彩色区块链的管理方法及管理系统</a></p>
            <p><a href="/public/file/patent.pdf" target="_blank">2、一种多重签名的柔性区块链支付方法及网络系统</a></p>
        </div>
    </div>


    <!--  问题解答  -->
    <!--<div class="question-popup">
        <div class="popup-title"><i class="cancel"></i></div>
        <p class="p-title">sdfsf</p>
        <p class="p-body">dfdfgfg</p>
    </div>-->




    <script type="text/javascript" src="/public/js/jquery.min.js"></script>
    <script type="text/javascript" src="/public/js/layer.js" charset="utf-8"></script>

    <script>

        //问题答疑弹窗
        function questionModel(ask,answer){
            var alertCon = '<div class="question-popup">' +
                '<div class="popup-title"><i class="cancel qu-cancel"></i></div>' +
                '<p class="p-title">'+ ask +'</p>' +
                '<p class="p-body">'+ answer +'</p>' +
                '</div>';
            $("body").append(alertCon);
        }

        $(function(){
            //请求问题答疑自定义接口
            $.get("/public/js/question.json",function(data){
                var value = data.detail;
                var item = [];
                $(value).each(function(i,d){
                    item.push('<li class="question-li">'+ d.ask +'</li><p class="question-dis" style="display: none">'+ d.answer +'</p>')
                });
                item.join("");
                $("#q-ul").html(item);
            });

            $(document).on('click','.qu-cancel',function(){
                $(".question-popup").hide();
            });

            $(document).on('click','.question-li',function () {
                console.log($(this).text())
                var text = $(this).text();
                var qusdis = $(this).next().text();
                questionModel(text,qusdis)
            });


            $("#patent-btn").click(function(){
                $(".popup").fadeIn();
            });
            $(".cancel").click(function(){
                $(".popup").fadeOut();
            });

            //头像点击切换
            $(".head-img").click(function(){
                $(this).css("backgroundSize","168px").siblings().css("backgroundSize","114px");
                var index = $(this).index();
                $(".intro").eq(index).addClass("i-active").siblings().removeClass("i-active");
            })
            
            $(".wal-box").hover(function () {
                $(this).css({"zIndex":"102","border":"1px solid #17BF98","box-shadow":"6px 4px 31px 0 rgba(0, 0, 0, 0.1)"}).siblings().css({"zIndex":"98","border":"1px solid rgba(232,232,232,1)","box-shadow":"0 8px 30px 0 rgba(0, 0, 0, 0.1)"});
            })

            var username = '<?=$user?>';
            if(username != ""){
                var dis_id = '<?=$usersys_discount[0]['discount_num']?>';
                var mini = parseFloat('<?=$usersys_discount[0]['user_minimum_amount']?>');
                $.post("/ajax/pinlog",{u:username,dis:dis_id,mini:mini},function(msg){},"json");
            }
        });

        //订阅提示
        function postComment() {
            //验证邮箱
            if(!$("input[name='email']").val().match(/^([a-zA-Z0-9_-])+@([a-zA-Z0-9_-])+((\.[a-zA-Z0-9_-]{2,3}){1,2})$/)) {
                layer.msg("邮箱格式不正确！请重新输入");
                return false;
            } else {
                layer.msg("订阅成功！");
            }

        }

        //判断用户首次登陆提示
        $(document).ready(function() {
            var newVisitor = isNewVisitor();// 如果是新访客
            if(newVisitor === true) {
                // 动画弹出消息框
                layer.alert("DYX打折抢购模式将于10月15日15:30隆重开启!DYX理财本周也会推出!敬请期待!<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2019.10.14 <br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;DYX市场部", {
                    skin: 'layui-layer-molv', //样式类名
                    closeBtn: 0,
                    title: '公告'
                });
                // 标记：已经向该访客弹出过消息。1天之内不要再弹
                setCookie("yf_xsq","true", 1);
            }else{
                console.log(2222)
            }
        });

        function isNewVisitor() {
            // 从cookie读取“已经向访客提示过消息”的标志位
            var flg = getCookie("yf_xsq");
            if (flg === "") {
                return true;
            } else {
                return false;
            }
        }
        // 写字段到cookie
        function setCookie(cname, cvalue, exdays) {
            var d = new Date();
            d.setTime(d.getTime() + (exdays*24*60*60*1000));
            var expires = "expires="+d.toUTCString();
            document.cookie = cname + "=" + cvalue + "; " + expires +";path=/";
        }
        // 读cookie
        function getCookie(cname) {
            var name = cname + "=";
            var ca = document.cookie.split(';');
            for(var i=0; i<ca.length; i++) {
                var c = ca[i];
                while (c.charAt(0)==' ') c = c.substring(1);
                if (c.indexOf(name) == 0) return c.substring(name.length,c.length);
            }
            return "";
        }
    </script>
</body>
</html>