<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>xcoinpay</title>
    <meta name="keywords" content="XCoinPay官网，XCoinPay区块链，区块链XCoinPay柔支付，区块链柔支付，柔支付，FomoXYT官网，FomoXYT，预约活动，区块链">
    <meta name="description" content="XCoinPay，XCoinPay，区块链，交易所，虚拟币交易">
    <link rel="shortcut icon" href="/public/images/xcoinpay.ico">
    <link rel="stylesheet" href="/public/css/index/main.css">
    <link rel="stylesheet" href="/public/css/website/managemoney.css">
</head>
<body>
<div class="box">
    <!--  公共头部  -->
    <?php load_view("inc/pc_nav");?>

    <!--  dyx理财  -->
    <div class="divBg pr">
        <!--<img src="/public/images/managemoney/divbg.png" width="100%" height="1535" alt="">-->
        <i class="title"></i>
        <p class="profit">静态收益</p>
        <div class="everyday">
            <img src="/public/images/managemoney/day.png" width="156" height="45" alt="">
            <p>随存随取，每日发放千分之五的利息，随时可以提现！</p>
        </div>
        <div class="month">
            <img src="/public/images/managemoney/month.png" width="267" height="45" alt="">
            <p>存入DYX锁仓，一个月后可提现，月息高达24%！</p>
        </div>
        <p class="art">注：冻结状态中的DYX不享受此政策。</p>
        <a class="btn" href="/user/personalcenter?type=personalcenter">立即参与</a>
        <div class="threeLevel">
            <p><img src="/public/images/managemoney/threeLevel.png" height="45" width="747" alt=""></p>
            <p class="threeArt">推荐人可拿到下级三代内一级所得利息的30%、</p>
            <p class="threeArt threeArt1">二级所得利息的20%、三级所得利息的10%。</p>
        </div>
    </div>


</div>


<script type="text/javascript" src="/public/js/jquery.min.js"></script>
<script type="text/javascript" src="/public/js/layer.js" charset="utf-8"></script>
</body>
</html>