<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>xcoinpay</title>
    <meta name="keywords" content="XCoinPay官网，XCoinPay区块链，区块链XCoinPay柔支付，区块链柔支付，柔支付，FomoXYT官网，FomoXYT，预约活动，区块链">
    <meta name="description" content="XCoinPay，XCoinPay，区块链，交易所，虚拟币交易">
    <link rel="shortcut icon" href="/public/images/xcoinpay.ico">
    <link rel="stylesheet" href="/public/css/index/main.css">
    <link rel="stylesheet" href="/public/css/website/offering.css">
</head>
<body>
    <div class="box">
        <!--  公共头部  -->
        <?php load_view("inc/pc_nav");?>

        <!--  DYX公募计划  -->
        <div class="dyx-box">
            <div class="warp-1200 dyx-bg pr">
                <p class="dyx-img"><img src="/public/images/website/dyx-img.png" width="873" height="690" alt=""></p>
                <p><a class="im-subscribe" href="JavaScript:alert('活动结束')" >活动结束</a></p><!--id="popupx"  useroffering-->
<!--                <p class="notes">注：DYX群主额度福利，仅开放给合作群主，如果您想参与兑换，请联系合作群主，并用合作群主的邀请码注册xcoinpay.io的官网账户后，即可在xcoinpay.io官网进行兑换。</p>-->
                <div>
                    <div class="dyx-discount">
                        <div style="text-align: left;">
                            <p>每个群主的兑换额度固定100USDT，兑换成本固定0.002USDT，在开盘价0.002USDT上涨一定比例后的基础上，官方将发起打折活动，预计每期都会有大量的人参与，而排名机制会让很多人在交易平台购买DYX参与活动，这样每期活动都会拉涨价格。</p>
                        </div>
                    </div>
                </div>
                <div class="pr">
                    <i class="dyx-decorate1"></i>
                    <i class="dyx-arrow"></i>
                    <div class="dyx-proportion">
                        <ul class="ov dyx-ul1">
                            <li style="line-height: 42px;width: 312px;" class="fl"><p>兑换成本</p></li>
                            <li style="line-height: 42px;width: 312px;" class="fl"><p>兑换币种</p></li>
                            <li style="line-height: 42px;width: 312px;" class="fl"><p>代币名称</p></li>
                        </ul>
                        <ul class="ov dyx-ul2">
                            <li style="width: 312px;" class="fl"><p>0.002USDT</p></li>
                            <li style="width: 312px;" class="fl"><p>USDT</p></li>
                            <li style="width: 312px;" class="fl"><p>DYX</p></li>
                        </ul>
                    </div>
                </div>
                <div class="pr" style="margin-bottom: 100px;">
                    <i class="dyx-decorate2"></i>
                    <p class="profit-title"><img src="/public/images/website/dyx-line.png" width="33" height="21" alt=""><span>收益计算</span><img src="/public/images/website/dyx-line.png" width="33" height="21" alt=""></p>
                    <div class="dyx-profit">
                        <p class="dyx-mark"><img src="/public/images/website/dyx-star-small.png" width="18" height="17" alt="">注明<img src="/public/images/website/dyx-star-small.png" width="18" height="17" alt=""></p>
                        <p class="dyx-m-text">在上线交易之前，您持有的DYX会全部解锁。</p>
                        <p class="dyx-m-text">兑换仅接受USDT，兑换仅在官网xcoinpay.io进行。</p>
                    </div>
                </div>

            </div>
        </div>
    </div>

    <!--  开启弹窗  -->
    <div class="popup-box" id="open">
        <div class="popup-title">兑换DYX</div>
        <div class="popup-body">
            <p class="body-t">≈ <span id="token_type" class="token_type">0</span> USDT</p>
            <input type="number" class="body-money" id="money-num-open" placeholder="0" value="" step="10">
            <p class="body-balance">账户余额：<?=$user_usdt?> USDT</p>
            <p class="body-balance">个人额度余额：xx USDT</p>
            <p class="body-balance">总额度余额：xx USDT</p>
            <p style="font-size: 14px;color: #091928;margin-bottom: 5px;">兑换比例：1usdt=555.555个DYX</p>
            <p style="font-size: 14px;color: #091928;margin-bottom: 18px;">可获得DYX数量：xx个</p>
            <p class="minmun"><span style="color: red;">*</span>最低兑换资金20usdt</p>
        </div>
        <div class="popup-foot">
            <span class="cancel">取消</span>
            <span class="sure-buy" onclick="reserve('open')">确定兑换</span>
        </div>
    </div>


    <script type="text/javascript" src="/public/js/jquery.min.js"></script>
    <script>
        $(function(){
            //立即预约
            $("#popupx").click(function(){
                $("#open").fadeIn();
            });
            $(".cancel").click(function(){
                $("#open").fadeOut();
            });

            //键入其他金额
            $(document).on("keyup",'.body-money',function(){
                //$(".balance-box").find("p").removeClass('b-active');
                let usdt = $(".body-money").val();
                $(".token_type").html(usdt);
            });


        })

    </script>
</body>
</html>