<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>xcoinpay</title>
    <meta name="keywords" content="XCoinPay官网，XCoinPay区块链，区块链XCoinPay柔支付，区块链柔支付，柔支付，FomoXYT官网，FomoXYT，预约活动，区块链">
    <meta name="description" content="XCoinPay，XCoinPay，区块链，交易所，虚拟币交易">
    <link rel="shortcut icon" href="/public/images/xcoinpay.ico">
    <link rel="stylesheet" href="/public/css/index/main.css">
    <link rel="stylesheet" href="/public/css/website/offering.css">
</head>
<body>
    <div class="box">
        <!--  公共头部  -->
        <?php load_view("inc/pc_nav");?>

        <!--  DYX公募计划  -->
        <div class="dyx-box">
            <div class="warp-1200 dyx-bg pr">
                <p class="dyx-img"><img src="/public/images/website/dyx-img.png" width="873" height="690" alt=""></p>
<!--                <p><a class="im-subscribe" href="javascript:alert('暂未开放');">立即兑换</a></p>-->
                <p><a class="im-subscribe" id="popupx" href="javascript:void(0)">立即兑换</a></p>
                <!--<p class="notes">注：DYX群主额度福利，仅开放给合作群主，如果您想参与兑换，请联系合作群主，并用合作群主的邀请码注册xcoinpay.io的官网账户后，即可在xcoinpay.io官网进行兑换。</p>-->
                <div>
                    <div class="dyx-discount">
                        <div style="text-align: left;">
                            <p>官方在上线交易所价格的基础上，以9折优惠送出DYX群主额度福利，所有合作群主均享有此优惠。</p>
                            <p>DYX群主额度福利兑换成功后，获得的DYX代币10%流通，90%锁仓，锁仓部分20~40天内动态释放完毕。</p>
                            <p>每个用户额度仅限1000USDT</p>
                        </div>
                    </div>
                </div>
                <div class="pr">
                    <i class="dyx-decorate1"></i>
                    <i class="dyx-arrow"></i>
                    <div class="dyx-proportion">
                        <ul class="ov dyx-ul1">
                            <li class="fl"><p>优惠</p></li>
                            <li class="fl"><p>流通</p><p>比例</p></li>
                            <li class="fl"><p>锁仓</p><p>比例</p></li>
                            <li class="fl"><p>锁仓</p><p>日期</p></li>
                            <li class="fl"><p>上线</p><p>价格</p></li>
                            <li class="fl"><p>兑换</p><p>成本</p></li>
                            <li class="fl"><p>兑换</p><p>币种</p></li>
                            <li class="fl"><p>代币</p><p>名称</p></li>
                        </ul>
                        <ul class="ov dyx-ul2">
                            <li class="fl"><p>10%</p></li>
                            <li class="fl"><p>10%</p></li>
                            <li class="fl"><p>90%</p></li>
                            <li class="fl"><p>20~40</p><p>天</p></li>
                            <li class="fl"><p>0.002</p><p>USDT</p></li>
                            <li class="fl"><p>0.0018</p><p>USDT</p></li>
                            <li class="fl"><p>USDT</p></li>
                            <li class="fl"><p>DYX</p></li>
                        </ul>
                    </div>
                </div>
                <div class="pr" style="margin-bottom: 100px;">
                    <i class="dyx-decorate2"></i>
                    <p class="profit-title"><img src="/public/images/website/dyx-line.png" width="33" height="21" alt=""><span>收益计算</span><img src="/public/images/website/dyx-line.png" width="33" height="21" alt=""></p>
                    <div class="dyx-profit">
                        <p class="dyx-t">第一阶段</p>
                        <p class="dyx-b">如果您能成功兑换群主额度，那么您的兑换成本是1DYX=0.0018USDT，开盘后，稳定开盘价格在0.002USDT，您可以卖出10%的筹码，这部分收益最低10%。</p>
                        <p class="dyx-t">第二阶段</p>
                        <p class="dyx-b">在开盘价0.002USDT上涨一定比例后的基础上，官方将发起打折活动，预计每期都会有大量的人参与，而排名机制会让很多人在交易平台购买DYX参与活动，这样每期活动都会拉涨价格，持有者可以阶段性卖出90%的筹码。</p>
                        <p class="dyx-mark"><img src="/public/images/website/dyx-star-small.png" width="18" height="17" alt="">注明<img src="/public/images/website/dyx-star-small.png" width="18" height="17" alt=""></p>
                        <p class="dyx-m-text">1、数据如有变动，即同步到每位投资人。</p>
                        <p class="dyx-m-text">2、USDT恒定以1USDT= 7.16 CNY来计算。</p>
                        <p class="dyx-m-text">3、解锁时间从上线交易所时开始计算。</p>
                        <p class="dyx-m-text">4、根据二级市场的价格和深度来确定动态解锁时间。</p>
                        <p class="dyx-m-text">5、DYX代币合约地址：<span class="dyx-m-text2">0x042f972ac93404f0fcbe4e3a0729f0b395232106。</span></p>
                        <p class="dyx-m-text">6、兑换仅接受USDT，兑换仅在官网xcoinpay.io进行。</p>
                    </div>
                </div>

            </div>
        </div>
    </div>

    <!--  开启弹窗  -->
    <div class="popup-box" id="open">
        <div class="popup-title">兑换DYX</div>
        <div class="popup-body">
            <p class="body-t">≈ <span id="token_type" class="token_type">0</span> USDT</p>
            <input type="number" class="body-money" id="money-num-open" placeholder="0" value="0" step="10">
            <p class="body-balance">账户余额：<?=$user_usdt?> USDT</p>
            <p class="body-balance">您的可兑换总额度：<?=$user_fixed_amount?> USDT</p>
            <p class="body-balance" style="color: red;">您的剩余可兑换额度：<?=$user_available_amount?> USDT</p>
<!--            <p class="body-balance" style="color: red;">群主活动剩余可兑换总额度：--><?//=$group_balance?><!-- USDT</p>-->
            <p style="font-size: 16px;color: #57646f;margin-bottom: 5px;">兑换比例：1usdt=555.555个DYX</p>
            <p style="font-size: 16px;color: #57646f;margin-bottom: 5px;">可获得DYX数量：<span id="money-num-dyx">0</span>个</p>
            <p style="font-size: 16px;color: #57646f;margin-bottom: 5px;">最低兑换资金20usdt</p>
        </div>
        <div class="popup-foot">
            <span class="cancel">取消</span>
            <span class="sure-buy" onclick="reserve()">确定兑换</span>
        </div>
    </div>


    <script type="text/javascript" src="/public/js/jquery.min.js"></script>
    <script type="text/javascript" src="/public/js/layer.js" charset="utf-8"></script>
    <script>
        $(function(){
            //立即预约
            $("#popupx").click(function(){
                $("#open").fadeIn();
            });
            $(".cancel").click(function(){
                $("#open").fadeOut();
            });
            //键入其他金额
            $(document).on("keyup",'.body-money',function(){
                let usdt = parseFloat($(".body-money").val());
                if(isNaN(usdt)){
                    usdt = 0;
                }else{
                    usdt = usdt;
                }
                $(".token_type").html(usdt);
                usdt = mul(usdt , 555.55);
                $("#money-num-dyx").text(usdt);
            });
        });
        function mul(a, b) {
            var c = 0;
            var d = a.toString();
            var e = b.toString();
            try {
                c += d.split(".")[1].length;
            } catch (f) {}
            try {
                c += e.split(".")[1].length;
            } catch (f) {}
            return Number(d.replace(".", "")) * Number(e.replace(".", "")) / Math.pow(10, c);
        }
        function reserve(){
            var usdt = parseFloat("<?=$user_usdt?>");
            var input_usdt = parseFloat($("#money-num-open").val());
            var dyx = parseFloat($("#money-num-dyx").text());
            var user = "<?=$user?>";
            if(usdt-input_usdt < 0){
                layer.msg('剩余最低兑换资金20usdt', {
                    time: 20000, //20s后自动关闭
                    btn: ['充值', '取消'],
                    yes:function () {
                        window.location.href='/user/personalcenter';
                    }
                });
                return false;
            }
            if(input_usdt < 20){
                layer.msg("最低兑换资金20usdt");
                return false;
            }
            $.post("/ajax/ajaxuseroffering",{usdt:usdt,input_usdt:input_usdt,dyx:dyx,user:user},function (msg) {
                if(msg.code == 1){
                    layer.msg(msg.msg);
                    setTimeout(function () {
                        window.location.href = location.href
                    },1000);
                }else{
                    layer.msg(msg.msg);
                }
            },"json");
        }
    </script>
</body>
</html>