<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>xcoinpay</title>
    <meta name="keywords" content="XCoinPay官网，XCoinPay区块链，区块链XCoinPay柔支付，区块链柔支付，柔支付，FomoXYT官网，FomoXYT，预约活动，区块链">
    <meta name="description" content="XCoinPay，XCoinPay，区块链，交易所，虚拟币交易">
    <link rel="shortcut icon" href="/public/images/xcoinpay.ico">
    <link rel="stylesheet" href="/public/css/index/main.css">
    <link rel="stylesheet" href="/public/css/website/offering.css">
</head>
<body>
    <div class="box">
        <!--  公共头部  -->
        <?php load_view("inc/pc_nav");?>

        <!--  DYX公募计划  -->
        <div class="dyx-box">
            <div class="warp-1200 dyx-bg pr">
                <p class="dyx-img"><img src="/public/images/website/dyx-img.png" width="873" height="690" alt=""></p>
                <?php if($status == -1): ?>
                    <p><a class="im-subscribe" href="javascript:void(0)" onclick="groupsend()">立即申请</a></p>
                <?php elseif($status == 1):  ?>
<!--                    <img src="/public/images/website/kefu.jpg" style="width: 200px;margin-top: -200px;"/><p style="text-align: center;text-align: center;font-weight: bold;color: #fbfbfb;padding: 10px 0;">请添加客服微信二维码</p>-->
                    <p><a class="im-subscribe" id="popupx" href="javascript:void(0)">立即兑换</a></p>
                <?php else: ?>
                    <div>
                        <img src="/public/images/website/kefu2.jpg" style="width: 200px;margin-top: -200px;" />
                        <p style="text-align: center;text-align: center;font-weight: bold;color: #fbfbfb;padding: 10px 0;">申请成功，请添加客服，进行审核，审核后即可进行兑换</p>
                    </div>
                    <!--<p><a class="im-subscribe" href="javascript:void(0)">等待审核</a></p>-->
                <?php endif; ?>
                <div>
                    <div class="dyx-discount">
                        <div style="text-align: left;">
                            <p>每个群主的兑换额度固定100USDT，兑换成本固定0.002USDT，在开盘价0.002USDT上涨一定比例后的基础上，官方将发起打折活动，预计每期都会有大量的人参与，而排名机制会让很多人在交易平台购买DYX参与活动，这样每期活动都会拉涨价格。</p>
                        </div>
                    </div>
                </div>
                <div class="pr">
                    <i class="dyx-decorate1"></i>
                    <i class="dyx-arrow"></i>
                    <div class="dyx-proportion">
                        <ul class="ov dyx-ul1">
                            <li style="line-height: 42px;width: 312px;" class="fl"><p>兑换成本</p></li>
                            <li style="line-height: 42px;width: 312px;" class="fl"><p>兑换币种</p></li>
                            <li style="line-height: 42px;width: 312px;" class="fl"><p>代币名称</p></li>
                        </ul>
                        <ul class="ov dyx-ul2">
                            <li style="width: 312px;" class="fl"><p>0.002USDT</p></li>
                            <li style="width: 312px;" class="fl"><p>USDT</p></li>
                            <li style="width: 312px;" class="fl"><p>DYX</p></li>
                        </ul>
                    </div>
                </div>
                <div class="pr" style="margin-bottom: 100px;">
                    <i class="dyx-decorate2"></i>
                    <p class="profit-title"><img src="/public/images/website/dyx-line.png" width="33" height="21" alt=""><span>收益计算</span><img src="/public/images/website/dyx-line.png" width="33" height="21" alt=""></p>
                    <div class="dyx-profit">
                        <p class="dyx-mark"><img src="/public/images/website/dyx-star-small.png" width="18" height="17" alt="">注明<img src="/public/images/website/dyx-star-small.png" width="18" height="17" alt=""></p>
                        <p class="dyx-m-text">在上线交易之前，您持有的DYX会全部解锁。</p>
                        <p class="dyx-m-text">兑换仅接受USDT，兑换仅在官网xcoinpay.io进行。</p>
                    </div>
                </div>

            </div>
        </div>
    </div>

    <!--  开启弹窗  -->
    <div class="popup-box" id="open">
        <div class="popup-title">兑换DYX</div>
        <div class="popup-body">
            <p class="body-t">≈ <span id="token_type" class="token_type">0</span> USDT</p>
            <input type="number" class="body-money" id="money-num-open" placeholder="0" value="0" step="10">
            <p class="body-balance">账户余额：<?=$user_usdt?> USDT</p>
            <p class="body-balance">您的可兑换总额度：<?=($user=='15338864563')?2000:100?> USDT</p>
            <p class="body-balance" style="color: red;">您的剩余可兑换额度：<?=$user_available_amount?> USDT</p>
<!--            <p class="body-balance" style="color: red;">群主活动剩余可兑换总额度：--><?//=$group_balance?><!-- USDT</p>-->
            <p style="font-size: 16px;color: #57646f;margin-bottom: 5px;">兑换比例：1usdt=250个DYX</p>
            <p style="font-size: 16px;color: #57646f;margin-bottom: 5px;">可获得DYX数量：<span id="money-num-dyx">0</span>个</p>
            <p style="font-size: 16px;color: #57646f;margin-bottom: 5px;">最低兑换资金20usdt</p>
        </div>
        <div class="popup-foot">
            <span class="cancel">取消</span>
            <span class="sure-buy" onclick="reserve()">确定兑换</span>
        </div>
    </div>
    <script type="text/javascript" src="/public/js/jquery.min.js"></script>
    <script type="text/javascript" src="/public/js/layer.js" charset="utf-8"></script>
    <script>
        $(function(){
            //立即预约
            $("#popupx").click(function(){
                $("#open").fadeIn();
            });
            $(".cancel").click(function(){
                $("#open").fadeOut();
            });
            //键入其他金额
            $(document).on("keyup",'.body-money',function(){
                let usdt = parseFloat($(".body-money").val());
                if(isNaN(usdt)){
                    usdt = 0;
                }else{
                    usdt = usdt;
                }
                $(".token_type").html(usdt);
                usdt = mul(usdt , 250);
                $("#money-num-dyx").text(usdt);
            });
            $("#money-num-open").focus(function () {
                $("#money-num-open").val(null);
            });
        });
        function mul(a, b) {
            var c = 0;
            var d = a.toString();
            var e = b.toString();
            try {
                c += d.split(".")[1].length;
            } catch (f) {}
            try {
                c += e.split(".")[1].length;
            } catch (f) {}
            return Number(d.replace(".", "")) * Number(e.replace(".", "")) / Math.pow(10, c);
        }
        function reserve(){
            var usdt = parseFloat("<?=$user_usdt?>");
            var input_usdt = parseFloat($("#money-num-open").val());
            var dyx = parseFloat($("#money-num-dyx").text());
            var user = "<?=$user?>";
            if(usdt-input_usdt < 0){
                layer.msg('剩余最低兑换资金20usdt', {
                    time: 20000, //20s后自动关闭
                    btn: ['充值', '取消'],
                    yes:function () {
                        window.location.href='/user/personalcenter';
                    }
                });
                return false;
            }
            if(input_usdt < 20){
                layer.msg("最低兑换资金20usdt");
                return false;
            }

            $.post("/ajax/ajaxuseroffering2",{usdt:usdt,input_usdt:input_usdt,dyx:dyx,user:user},function (msg) {
                if(msg.code == 1){
                    layer.msg("兑换成功，请到个人资金里面查收");
                    setTimeout(function () {
                        window.location.href = location.href
                    },1000);
                }else{
                    layer.msg(msg.msg);
                }
            },"json");
        }
        function groupsend(){
            var user = '<?=$user?>';
            var usdt = '<?=$user_usdt?>';
            if(usdt < 100){
                layer.msg("低于最低活动参与资金100usdt");
                return false;
            }
//            //页面层-自定义
//            layer.open({
//                type: 1,
//                title: false,
//                closeBtn: 0,
//                shadeClose: true,
//                area: '440px',
//                skin: 'yourclass',
//                content: '<img src="/public/images/website/kefu2.jpg"/><p style="text-align: center;font-weight: bold;color: #000000;padding: 10px 0;">申请成功，请添加客服，进行审核，审核后即可进行兑换</p>'
//            });
            $.post("/ajax/dyxusergroup",{username:user},function(msg){
                $(".sure-buy").hide();
                layer.msg(msg.msg);
                window.location.href = location.href;
            },"json");
            
        }
    </script>
</body>
</html>