<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>xcoinpay</title>
    <meta name="keywords" content="FomoXYT官网，FomoXYT，预约活动，区块链">
    <meta name="description" content="FomoXYT，区块链，交易所，虚拟币交易">
    <link rel="shortcut icon" href="/public/images/xcoinpay.ico">
    <link rel="stylesheet" href="/public/css/index/main.css">
    <link rel="stylesheet" href="/public/css/index/login.css">
</head>
<body>
    <div class="box">
        <!--  head  -->
        <div class="nav-bar">
            <div class="main">
                <a href="/website/index" class="logo">云翻</a>
                <ul class="login-box">
                    <li><a href="/index/login">登录</a></li>
                    <li class="select"><a href="/index/register">注册</a></li>
                </ul>
            </div>
        </div>

        <!--  form  -->
        <div class="form-box">
            <div class="form-warp">
                <i class="login-logo"></i>
                <form class="data-box" action="/index/login" method="post">
                    <div class="tel"><input type="text" placeholder="请输入账号" name="username" value="" required></div>
                    <div class="pwd"><input type="password" placeholder="请输入密码" name="userpass" value="" required></div>
                    <div class="forget-box">
                        <a class="num-register" href="/index/register">账号注册</a>
                        <a class="forget-pwd" href="/index/forgetpwd">忘记密码</a>
                    </div>
                    <button class="submit-btn" type="submit">登录</button>
                </form>
            </div>
            <!--  cp  -->
            <!--<div class="cp"><p>2019 © FomoXYT.com 声明官方不参与活动币   合约Github开源代码  开发者@狗狗币微博  平台微信  测试</p></div>-->
        </div>
    </div>
</body>
</html>