<?php error_reporting(0); ?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>xcoinpay</title>
    <meta name="keywords" content="FomoXYT官网，FomoXYT，预约活动，区块链">
    <meta name="description" content="FomoXYT，区块链，交易所，虚拟币交易">
    <meta http-equiv="Refresh" content="3; url=http://www.xcoinpay.io/website/index" />
    <link rel="shortcut icon" href="/public/images/xcoinpay.ico">
    <link rel="stylesheet" href="/public/css/index/main.css">
    <link rel="stylesheet" href="/public/css/index/index.css">
</head>
<body>
<div class="box">
    <!--  head  -->
    <?php load_view("inc/pc_nav");?>
</div>


<script type="text/javascript" src="/public/js/jquery.min.js"></script>
<script type="text/javascript" src="/public/js/layer.js" charset="utf-8"></script>
<script>
    $(function(){
        layer.alert('404页面不存在');
    })
</script>
</body>
</html>