<!DOCTYPE html>
<html class="x-admin-sm">
<head>
    <meta charset="UTF-8">
    <title>FOMO拍卖活动</title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <link rel="stylesheet" href="/public/css/font.css">
    <link rel="stylesheet" href="/public/css/xadmin.css">
    <link rel="stylesheet" href="/public/css/glayui.css?t=1568076536509" media="all">
    <link rel="stylesheet" href="/public/css/global.css?t=1568076536509-11" media="all">
    <script type="text/javascript" src="/public/js/jquery.min.js"></script>
    <script type="text/javascript" src="/public/js/glayer.js"></script>
    <script src="/public/lib/layui/layui.js" charset="utf-8"></script>
    <script type="text/javascript" src="/public/js/xadmin.js"></script>
    <style>
        .layui-form-onswitch {border-color: #5FB878;background-color: #5FB878; }
        .layui-form-label, .layui-form-mid, .layui-form-select, .layui-input-block, .layui-input-inline, .layui-textarea{margin-left: 0;}
        .layui-fluid{padding: 0;}
    </style>
</head>
<body>
    <div class="x-nav">
        <span class="layui-breadcrumb">
            <a href="">首页</a>
            <a href="">活动管理</a>
            <a><cite>FOMO拍卖活动</cite></a>
        </span>
        <a class="layui-btn layui-btn-small" style="line-height:1.6em;margin-top:3px;float:right" onclick="location.reload()" title="刷新">
            <i class="layui-icon layui-icon-refresh" style="line-height:30px"></i>
        </a>
    </div>
    <div class="layui-fluid">
        <div class="layui-row layui-col-space15">
            <div class="layui-col-md12">

                <div class="layui-card">
                    <div class="layui-card-header">
                        <button class="layui-btn" onclick="window.location.href='/admin/auctionadd'"><i class="layui-icon"></i>添加</button>
                    </div>
                    <div class="layui-card-body ">
                        <table class="layui-table layui-form">
                            <thead>
                            <tr>
                                <th>拍卖期次</th>
                                <th>开启时间</th>
                                <th>结束时间</th>
                                <th>拍卖奖品</th>
                                <th>获胜者</th>
                                <th>买单者</th>
                                <th>当前最大金额</th>
                                <th>拍卖状态</th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php foreach ($arrdata as $k=>$v): ?>
                            <tr>
                                <td>第<?=conversion($v['f_id'])?>期</td>
                                <td><?=date("Y-m-d H:i:s",$v['start_time'])?></td>
                                <td><?=date("Y-m-d H:i:s",$v['end_time'])?></td>
                                <th><?=$v['award_btc']?>BTC &nbsp;<?=$v['award_usdt']?>USDT &nbsp;<?=$v['award_xyt']?>XYT &nbsp;<?=$v['award_dyx']?>DYX &nbsp;<?=$v['award_rntp']?>RNTP &nbsp;<?=$v['award_stock']?>分红股</th>
                                <td>第<?=$v['winner']?>名</td>
                                <td>第<?=$v['payer']?>名</td>
                                <td><?=$v['fomo_price']?>XYT</td>
                                <td>
                                    <div class="layui-form" action="">
                                        <div class="layui-form-item">
                                            <div class="layui-input-block">
                                                <input type="checkbox" name="close" lay-skin="switch" lay-text="ON|OFF">
                                                <?php if($v['status'] == 1):?>
                                                    <div class="layui-unselect layui-form-switch" lay-skin="_switch" >
                                                        <em>OFF</em>
                                                        <i></i>
                                                    </div>
                                                <?php else: ?>
                                                    <div id="send" class="layui-unselect layui-form-switch layui-form-onswitch" lay-skin="_switch" >
                                                        <em id="sw">ON</em>
                                                        <i></i>
                                                    </div>
                                                <?php endif; ?>
                                            </div>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                            <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                    <div class="layui-card-body ">
                        <?=$showstr?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>
<script>
    var sendNode = document.getElementById("send");
    sendNode.onclick = function(){
        var swNode = document.getElementById("sw");
        if(swNode.innerHTML == 'OFF'){
            sendNode.setAttribute("class","layui-unselect layui-form-switch layui-form-onswitch");
            swNode.innerHTML = "ON";
        }else{
            sendNode.setAttribute("class","layui-unselect layui-form-switch");
            swNode.innerHTML = "OFF";
        }
    };
</script>