<!DOCTYPE html>
<html class="x-admin-sm">

<head>
    <meta charset="UTF-8">
    <title>排名额度分配</title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width,user-scalable=yes, minimum-scale=0.4, initial-scale=0.8,target-densitydpi=low-dpi" />
    <link rel="stylesheet" href="/public/css/font.css">
    <link rel="stylesheet" href="/public/css/xadmin.css">
    <script type="text/javascript" src="/public/js/jquery.min.js"></script>
    <script src="/public/lib/layui/layui.js" charset="utf-8"></script>
    <script type="text/javascript" src="/public/js/xadmin.js"></script>
</head>

<body>
<div class="x-nav">
            <span class="layui-breadcrumb">
                <a href="">首页</a>
                <a href="">用户管理</a>
                <a><cite>排名额度分配</cite></a>
            </span>
    <a class="layui-btn layui-btn-small" style="line-height:1.6em;margin-top:3px;float:right" onclick="location.reload()" title="刷新">
        <i class="layui-icon layui-icon-refresh" style="line-height:30px"></i>
    </a>
</div>
<div class="layui-fluid">
    <div class="layui-row layui-col-space15">

        <div class="layui-col-md12">

            <div class="layui-card">
                <div class="layui-card-body" style="width:500px;">
                    <form action="/admin/bulidranking" method="post">
                        <table class="layui-table layui-form">
                            <thead>
                            <tr>
                                <th>个人排名额度</th>
                                <th>团队排名额度</th>
                                <th>操作</th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <td><input type="number" class="layui-input" name="personal" value="<?=$data['personal']?>" /></td>
                                <td><input type="number" class="layui-input" name="team" value="<?=$data['team']?>" /></td>
                                <td>
                                    <input type="hidden" name="id" value="<?=$data['id']?>">
                                    <input type="submit" class="layui-btn"  value="保存">
                                </td>
                            </tr>
                            </tbody>
                        </table>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
</body>

<script>

//
//    $.post("/admin/ajaxuser",{data:s_text,user:uid},function(msg){
//        layer.msg(msg.message)
//    },"json");

</script>

</html>