<!DOCTYPE html>
<html class="x-admin-sm">
    
    <head>
        <meta charset="UTF-8">
        <title>添加打折活动</title>
        <meta name="renderer" content="webkit">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta name="viewport" content="width=device-width,user-scalable=yes, minimum-scale=0.4, initial-scale=0.8,target-densitydpi=low-dpi" />
        <link rel="stylesheet" href="/public/css/font.css">
        <link rel="stylesheet" href="/public/css/xadmin.css">
        <script type="text/javascript" src="/public/js/jquery.min.js"></script>
        <script type="text/javascript" src="/public/js/layer.js" charset="utf-8"></script>
        <script type="text/javascript" src="/public/lib/layui/layui.js" charset="utf-8"></script>
        <script type="text/javascript" src="/public/js/xadmin.js"></script>
        <style>
            .layui-form-label{width: 200px;padding: 5px 15px;}
            .x-admin-sm .layui-btn{padding: 0 30px;}
        </style>
    </head>
    <body>
    <div class="x-nav">
            <span class="layui-breadcrumb">
                <a href="">首页</a>
                <a href="/admin/discount">活动管理</a>
                <a>
                    <cite>添加打折活动</cite></a>
            </span>
        <a class="layui-btn layui-btn-small" style="line-height:1.6em;margin-top:3px;float:right" onclick="location.reload()" title="刷新">
            <i class="layui-icon layui-icon-refresh" style="line-height:30px"></i>
        </a>
    </div>
    <div class="layui-fluid">
        <div class="layui-row layui-col-space15">
            <div class="layui-col-md12">
                <div class="layui-card">
                    <div class="layui-card-body ">

                        <div class="layui-fluid">
                            <div class="layui-row">
                                <form class="layui-form" action="/admin/discountadd" method="post">
                                    <div class="layui-form-item">
                                        <label for="username" class="layui-form-label">
                                            <span class="x-red">*</span>打折活动期次
                                        </label>
                                        <div class="layui-input-inline">
                                            <input type="text" id="username" name="discount_num" required="" lay-verify="discount_num"
                                                   autocomplete="off" class="layui-input">
                                        </div>
                                        <div class="layui-form-mid layui-word-aux">
                                            <span class="x-red">*</span>(xx 期)
                                        </div>
                                    </div>
                                    <div class="layui-form-item">
                                        <label for="phone" class="layui-form-label">
                                            <span class="x-red">*</span>锁定交易所价
                                        </label>
                                        <div class="layui-input-inline" style="width: 400px;">
                                            <input type="text" placeholder="输入代币" name="token" required="" lay-verify="token" class="layui-input" style="width: 75px;float: left;margin-right: 10px;">
                                            <div style="line-height: 30px;display: inline-block;float: left;">代币 = &nbsp;</div>
                                            <input type="text" placeholder="输入USDT" name="usdt" id="usdt" required="" lay-verify="usdt"  class="layui-input" style="width: 74px;float: left;margin-right: 10px;">
                                            <div style="line-height: 30px;display: inline-block;">USDT</div>
                                            <input type="datetime-local" placeholder="请选择时间" name="dtime" required="" lay-verify="dtime" class="layui-input" style="width: 190px;float: left;margin-top: 20px;margin-right: 10px;">
                                            <div style="line-height: 30px;margin-top: 20px;"><span class="x-red">*</span>(X 年 X月)</div>
                                            <input type="text" placeholder="请输入交易所" name="exchange" required="" lay-verify="dtime" class="layui-input" style="width: 190px;float: left;margin-top: 20px;margin-right: 10px;">
                                        </div>
                                    </div>
                                    <div class="layui-form-item">
                                        <label for="L_email" class="layui-form-label">
                                            <span class="x-red">*</span>锁定85折价格
                                        </label>
                                        <div class="layui-input-inline">
                                            <input type="text" id="lock85_price" name="lock85_price" required="" lay-verify="lock85_price" readonly
                                                   autocomplete="off" class="layui-input" value="">
                                        </div>
                                        <div class="layui-form-mid layui-word-aux">
                                            <span class="x-red">*</span>(xx usdt)
                                        </div>
                                    </div>
                                    <div class="layui-form-item">
                                        <label for="L_email" class="layui-form-label">
                                            <span class="x-red">*</span>本期放出额度
                                        </label>
                                        <div class="layui-input-inline">
                                            <input type="text" id="unlock_price" name="unlock_price" required="" lay-verify="unlock_price"
                                                   autocomplete="off" class="layui-input">
                                        </div>
                                        <div class="layui-form-mid layui-word-aux">
                                            <span class="x-red">*</span>(xx usdt)
                                        </div>
                                    </div>
                                    <div class="layui-form-item">
                                        <label for="L_email" class="layui-form-label">
                                            <span class="x-red">*</span>折合代币数量
                                        </label>
                                        <div class="layui-input-inline">
                                            <input type="text" id="success_price" name="success_price" required="" lay-verify="success_price"
                                                   autocomplete="off" class="layui-input" readonly>
                                        </div>
                                        <div class="layui-form-mid layui-word-aux">
                                            <span class="x-red">*</span>(xx 代币)
                                        </div>
                                    </div>
                                    <div class="layui-form-item">
                                        <label for="L_email" class="layui-form-label">
                                            <span class="x-red">*</span>本期个人最低持币金额
                                        </label>
                                        <div class="layui-input-inline">
                                            <input type="text" id="user_minimum_amount" name="user_minimum_amount" required="" lay-verify="system_price"
                                                   autocomplete="off" class="layui-input">
                                        </div>
                                        <div class="layui-form-mid layui-word-aux">
                                            <span class="x-red">*</span>(xx usdt)
                                        </div>
                                    </div>
                                    <!--<div class="layui-form-item">
                                        <label for="phone" class="layui-form-label">
                                            <span class="x-red">*</span>打折活动礼包
                                        </label>
                                        <div class="layui-input-inline" style="width: 400px;">
                                            <input type="text" placeholder="请输入代币数量" name="discount_package_token" lay-verify="discount_package_token" class="layui-input" style="margin-right: 10px;width: 190px;float: left;">
                                            <div style="line-height: 30px;"><span class="x-red">*</span>(代币)</div>
                                            <input type="text" placeholder="请输入usdt数量" name="discount_package_usdt" lay-verify="discount_package_usdt"  class="layui-input" style="margin-right: 10px;width: 190px;float: left;margin-top: 20px;">
                                            <div style="line-height: 30px;margin-top: 20px;"><span class="x-red">*</span>(USDT)</div>
                                            <input type="text" placeholder="请输入xyt数量" name="discount_package_xyt" lay-verify="discount_package_xyt"  class="layui-input" style="margin-right: 10px;width: 190px;float: left;margin-top: 20px;">
                                            <div style="line-height: 30px;margin-top: 20px;"><span class="x-red">*</span>(XYT)</div>
                                            <input type="text" placeholder="请输入BTC数量" name="discount_package_btc" lay-verify="discount_package_btc"  class="layui-input" style="margin-right: 10px;width: 190px;float: left;margin-top: 20px;">
                                            <div style="line-height: 30px;margin-top: 20px;"><span class="x-red">*</span>(BTC)</div>
                                            <input type="text" placeholder="请输入分红股" name="discount_package_stock" lay-verify="discount_package_stock"  class="layui-input" style="margin-right: 10px;width: 190px;float: left;margin-top: 20px;">
                                            <div style="line-height: 30px;margin-top: 20px;"><span class="x-red">*</span>(分红股)</div>
                                        </div>
                                    </div>-->
                                    <div class="layui-form-item">
                                        <label for="L_repass" class="layui-form-label">
                                        </label>
                                        <a class="layui-btn layui-btn-normal" href="/admin/discount">返回</a>
                                        <button type="submit"  class="layui-btn">添加</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </body>


        <script>
            layui.use(['form', 'layer'],
            function() {
                $ = layui.jquery;
                var form = layui.form,
                layer = layui.layer;
                //监听提交
                form.on('submit(add)',
                    function() {
                        //关闭当前frame
                        xadmin.close();
                        // 可以对父窗口进行刷新
                        xadmin.father_reload();
                    });

            });
        </script>
        <script>
            var _hmt = _hmt || []; (function() {
                var hm = document.createElement("script");
                hm.src = "https://hm.baidu.com/hm.js?b393d153aeb26b46e9431fabaf0f6190";
                var s = document.getElementsByTagName("script")[0];
                s.parentNode.insertBefore(hm, s);
            })();

            $(function(){
               $("#usdt").blur(function(){
                    var usdtVal = $(this).val();
                    var data85 = usdtVal*0.85;
                    $("#lock85_price").val(data85);
               });
               $("#unlock_price").blur(function(){
                   var sysVal = $(this).val();
                   var data85 = sysVal*0.85;
                   $("#success_price").val(data85);
               });
            });
        </script>
    </body>

</html>
