<!DOCTYPE html>
<html class="x-admin-sm">
    
    <head>
        <meta charset="UTF-8">
        <title>打折活动</title>
        <meta name="renderer" content="webkit">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta name="viewport" content="width=device-width,user-scalable=yes, minimum-scale=0.4, initial-scale=0.8,target-densitydpi=low-dpi" />
        <link rel="stylesheet" href="/public/css/font.css">
        <link rel="stylesheet" href="/public/css/xadmin.css">
        <script type="text/javascript" src="/public/js/jquery.min.js"></script>
        <script type="text/javascript" src="/public/js/layer.js" charset="utf-8"></script>
        <script src="/public/lib/layui/layui.js" charset="utf-8"></script>
        <script type="text/javascript" src="/public/js/xadmin.js"></script>
    </head>

    <body>
        <div class="x-nav">
            <span class="layui-breadcrumb">
                <a href="">首页</a>
                <a href="">活动管理</a>
                <a>
                    <cite>打折活动</cite></a>
            </span>
            <a class="layui-btn layui-btn-small" style="line-height:1.6em;margin-top:3px;float:right" onclick="location.reload()" title="刷新">
                <i class="layui-icon layui-icon-refresh" style="line-height:30px"></i>
            </a>
        </div>
        <div class="layui-fluid">
            <div class="layui-row layui-col-space15">
                <div class="layui-col-md12">
                    <div class="layui-card">
                        <div class="layui-card-header">
                            <button class="layui-btn layui-btn-danger" onclick="delAll()">
                                <i class="layui-icon"></i>批量删除</button>
                            <button class="layui-btn" onclick="window.location.href='/admin/discountadd'">
                                <i class="layui-icon"></i>添加</button></div>
                        <div class="layui-card-body ">
                            <table class="layui-table layui-form">
                                <thead>
                                <tr>
                                    <th>打折活动期次</th>
                                    <th>用户预约额度</th>
                                    <th>本期最低额度</th>
                                    <th>交易所名称</th>
                                    <th>锁定交易所价格</th>
                                    <th>锁定85折价格</th>
                                    <th style="width: 250px;">本期放出额度</th>
                                    <th>折合代币数量</th>
                                    <th>系统卖出价格</th>
                                    <th>最终收益率</th>
                                    <th>状态</th>
                                </tr>
                                </thead>
                                <tbody>
                                <?php foreach ($arrdata as $k=>$v): ?>
                                    <tr>
                                        <td><?=$v['discount_num']?></td>
                                        <td><?=user_discount_price($v['discount_num'])?></td>
                                        <th><?=$v['user_minimum_amount']?>DYX</th>
                                        <td style="width: 250px; height: 29px;">
                                            <input type="text" name="exchange" class="layui-input price" style="float: left;width: 120px;" value="<?=$v['exchange']?>">
                                            <div class="status" style="float: left;margin-left: 10px;display: none;">
                                                <button type="button" class="layui-btn layui-btn-danger layui-btn-sm" onclick="dbnamed(this)"><i class="layui-icon">&#x1006;</i></button>
                                                <button type="button" class="layui-btn layui-btn-sm" onclick="dbname(this,'<?=$v['discount_num']?>')"><i class="layui-icon">&#xe605;</i></button>
                                            </div>
                                        </td>
                                        <td style="width: 250px; height: 29px;">
                                            <input type="number" name="exchange_price" class="layui-input price" style="float: left;width: 120px;" value="<?=$v['exchange_price']?>">
                                            <div class="status" style="float: left;margin-left: 10px;display: none;">
                                                <button type="button" class="layui-btn layui-btn-danger layui-btn-sm" onclick="dbmodify(this)"><i class="layui-icon">&#x1006;</i></button>
                                                <button type="button" class="layui-btn layui-btn-sm" onclick="dbmo(this,'<?=$v['discount_num']?>')"><i class="layui-icon">&#xe605;</i></button>
                                            </div>
                                        </td>
                                        <td><?=$v['lock85_price']?></td>

                                        <?php if($v['status'] == 0): ?>
                                            <td style="width: 250px; height: 29px;">
                                                <input type="number" value="<?=$v['unlock_price']?>" class="layui-input price" onkeyup="edit(this.value,this)" style="float: left;width: 120px;">
                                                <div class="status" style="float: left;margin-left: 10px;display: none;">
                                                    <button type="button" class="layui-btn layui-btn-danger layui-btn-sm" onclick="dbdel(this)"><i class="layui-icon">&#x1006;</i></button>
                                                    <button type="button" class="layui-btn layui-btn-sm" onclick="dbedit(this,'<?=$v['discount_num']?>')"><i class="layui-icon">&#xe605;</i></button>
                                                </div>
                                            </td>
                                            <td class="success_price"><?=$v['success_price']?></td>
                                        <?php else: ?>
                                            <td class="unlock_price"><?=$v['unlock_price']?></td>
                                            <td class="success_price"><?=$v['success_price']?></td>
                                        <?php endif; ?>
                                        <td><?=$v['system_price']?></td>
                                        <td><?=$v['income']?></td>
                                        <td>
                                        <?php if($v['status'] == 0): ?>
                                            <a title="结束活动" onclick="send(<?=$v['discount_num']?>,<?=$v['unlock_price']?>,<?=$v['exchange_price']?>)" href="javascript:void(0);" class="layui-btn layui-btn-xs">结束活动</a>
                                        <?php else: ?>
                                            <span style='color:red;'>已完结</span>
                                        <?php endif; ?>
                                        </td>
                                    </tr>
                                <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>

    <script>
    function send(dis_id,unlock_price,exchange_price){
        var total_price = parseInt(unlock_price);
        var exchange_price =  parseFloat(exchange_price);
        $.post("/ajax/ajaxdiscount",{dis_id:dis_id,unlock_price:total_price,exchange_price:exchange_price},function(msg){
        },"json");
    }
    //锁定交易所价格
    function dbnamed(tag) {
        tag.parentNode.style.display = "none";
    }
    function dbname(tag,id) {
        var data =  tag.parentNode.previousSibling.previousSibling.value;
        $.post("/ajax/editdiscount",{dis_id:id,price:data,type:"exchange"},function(msg){
            layer.msg(msg.msg);
        },"json");
        tag.parentNode.style.display = "none";
    }

    function dbmodify(tag) {
        tag.parentNode.style.display = "none";
    }
    function dbmo(tag,id) {
        var data =  parseFloat(tag.parentNode.previousSibling.previousSibling.value);
        $.post("/ajax/editdiscount",{dis_id:id,price:data,type:"exchange_price"},function(msg){
            layer.msg(msg.msg);
        },"json");
        tag.parentNode.style.display = "none";
    }

    //本期放出额度
    function edit(tag,that){
        that.parentNode.nextSibling.nextSibling.innerText = tag*0.85;
    }
    function dbedit(tag,id) {
        var data =  parseInt(tag.parentNode.previousSibling.previousSibling.value);
        $.post("/ajax/editdiscount",{dis_id:id,price:data,type:"unlock_price"},function(msg){
            layer.msg(msg.msg);
        },"json");
        tag.parentNode.style.display = "none";
    }
    function dbdel(tag) {
        tag.parentNode.style.display = "none";
    }

    $(function(){
        $(".price").focus(function () {
            $(this).next("div").show();
        });
    });
    </script>
</html>