<!DOCTYPE html>
<html class="x-admin-sm">
    
    <head>
        <meta charset="UTF-8">
        <title>DYX群主活动</title>
        <meta name="renderer" content="webkit">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta name="viewport" content="width=device-width,user-scalable=yes, minimum-scale=0.4, initial-scale=0.8,target-densitydpi=low-dpi" />
        <link rel="stylesheet" href="/public/css/font.css">
        <link rel="stylesheet" href="/public/css/xadmin.css">
        <script type="text/javascript" src="/public/lib/layui/layui.js" charset="utf-8"></script>
        <script type="text/javascript" src="/public/js/xadmin.js"></script>
        <!-- 让IE8/9支持媒体查询，从而兼容栅格 -->
    </head>
    <body>
        <div class="layui-fluid" style="background: #fff;">
            <div class="layui-row">
                <form class="layui-form" action="/admin/editdyx" method="post">
                    <div class="layui-form-item">
                        <label for="username" class="layui-form-label" style="width: 112px;">
                            <span class="x-red">*</span>DYX活动总额度
                        </label>
                        <div class="layui-input-inline">
                              <input type="text" name="dxy_total_group" lay-verify="dxy_total_group" class="layui-input" value="<?=$dyxdiscount['dxy_total_group']?>">
                        </div>
                    </div>
                    <div class="layui-form-item">
                        <label for="username" class="layui-form-label" style="width: 112px;">
                            <span class="x-red">*</span>会员活动额度
                        </label>
                        <div class="layui-input-inline">
                            <input type="text" name="dxy_total_member" lay-verify="dxy_total_member" class="layui-input" value="<?=$dyxdiscount['dxy_total_member']?>">
                        </div>
                    </div>
                    <div class="layui-form-item">
                        <label for="username" class="layui-form-label" style="width: 112px;">
                            <span class="x-red">*</span>群主活动额度
                        </label>
                        <div class="layui-input-inline">
                            <input type="text" name="dxy_toal_lord" lay-verify="dxy_toal_lord" class="layui-input" value="<?=$dyxdiscount['dxy_toal_lord']?>">
                        </div>
                    </div>
                    <div class="layui-form-item">
                        <label for="username" class="layui-form-label" style="width: 112px;">
                            <span class="x-red">*</span>新群主活动额度
                        </label>
                        <div class="layui-input-inline">
                            <input type="text" name="dyx_toal_new_lord" lay-verify="dyx_toal_new_lord" class="layui-input" value="<?=$dyxdiscount['dyx_toal_new_lord']?>">
                        </div>
                    </div>
                    <div class="layui-form-item">
                      <label for="L_repass" class="layui-form-label"></label>
                      <button type="submit"  class="layui-btn">保存</button>
                    </div>
              </form>
            </div>
        </div>
        <script>
            layui.use(['form', 'layer'],
            function() {
                $ = layui.jquery;
                var form = layui.form,
                layer = layui.layer;
                //监听提交
                form.on('submit(add)',
                    function() {
                        //关闭当前frame
                        xadmin.close();
                        // 可以对父窗口进行刷新
                        xadmin.father_reload();
                    });

            });
        </script>
        <script>
            var _hmt = _hmt || []; (function() {
                var hm = document.createElement("script");
                hm.src = "https://hm.baidu.com/hm.js?b393d153aeb26b46e9431fabaf0f6190";
                var s = document.getElementsByTagName("script")[0];
                s.parentNode.insertBefore(hm, s);
            })();
        </script>
    </body>

</html>
