<!DOCTYPE html>
<html class="x-admin-sm">
    <head>
        <meta charset="UTF-8">
        <title>欢迎页面-X-admin2.2</title>
        <meta name="renderer" content="webkit">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta name="viewport" content="width=device-width,user-scalable=yes, minimum-scale=0.4, initial-scale=0.8,target-densitydpi=low-dpi" />
        <link rel="stylesheet" href="/public/css/font.css">
        <link rel="stylesheet" href="/public/css/xadmin.css">
        <script src="/public/lib/layui/layui.js" charset="utf-8"></script>
        <script type="text/javascript" src="/public/js/xadmin.js"></script>
    </head>
    <body>
        <div class="x-nav">
            <span class="layui-breadcrumb">
                <a href="">首页</a>
                <a href="">用户管理</a>
                <a><cite>数据统计</cite></a>
            </span>
            <a class="layui-btn layui-btn-small" style="line-height:1.6em;margin-top:3px;float:right" onclick="location.reload()" title="刷新">
                <i class="layui-icon layui-icon-refresh" style="line-height:30px"></i>
            </a>
        </div>
        <div class="layui-fluid">
            <div class="layui-row layui-col-space15">
                <div class="layui-col-md12">
                    <div class="layui-card">
                        <div class="layui-card-header layui-h">平台DYX总存量：<cite style="color: #009688;font-style: normal;font-size: 30px;font-weight: 300;color: #009688;"><?=$datahost[0]['total']-$datatx[0]['total']?></cite>    &nbsp;&nbsp;平台DYX总提现量：<cite style="color: #009688;font-style: normal;font-size: 30px;font-weight: 300;color: #009688;"><?=$datatx[0]['total']?></cite>
                        </div>
                    </div>
                    <div class="layui-card">
                        <div class="layui-card-header layui-h">兑换模块数据（0.0018U）</div>
                        <div class="layui-card-body ">
                            <ul class="layui-row layui-col-space10 layui-this x-admin-carousel x-admin-backlog">
                                <li class="layui-col-md3 layui-col-xs6">
                                    <a href="javascript:;" class="x-admin-backlog-body">
                                        <h3>以0.0018U兑换的总金额USDT</h3>
                                        <p><cite><?=$data18[0]['usdt']?></cite></p>
                                    </a>
                                </li>
                                <li class="layui-col-md3 layui-col-xs6">
                                    <a href="javascript:;" class="x-admin-backlog-body">
                                        <h3>总共币数量DYX</h3>
                                        <p><cite><?=$data18[0]['total']?></cite></p>
                                    </a>
                                </li>
                                <li class="layui-col-md3 layui-col-xs6">
                                    <a href="javascript:;" class="x-admin-backlog-body">
                                        <h3>解锁10%数量DYX</h3>
                                        <p><cite><?=$data18[0]['dunlock']?></cite></p>
                                    </a>
                                </li>
                                <li class="layui-col-md3 layui-col-xs6">
                                    <a href="javascript:;" class="x-admin-backlog-body">
                                        <h3>已经提现数量DYX</h3>
                                        <p><cite><?=$data18[0]['wx']?></cite></p>
                                    </a>
                                </li>
                                <li class="layui-col-md3 layui-col-xs6">
                                    <a href="javascript:;" class="x-admin-backlog-body">
                                        <h3>锁定90%数量DYX</h3>
                                        <p><cite><?=$data18[0]['dlock']?></cite></p>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="layui-card">
                        <div class="layui-card-header layui-h">兑换模块数据（0.002U）</div>
                        <div class="layui-card-body ">
                            <ul class="layui-row layui-col-space10 layui-this x-admin-carousel x-admin-backlog">
                                <li class="layui-col-md3 layui-col-xs6">
                                    <a href="javascript:;" class="x-admin-backlog-body">
                                        <h3>以0.02U兑换的总金额USDT</h3>
                                        <p><cite><?=$data20[0]['usdt']?></cite></p>
                                    </a>
                                </li>
                                <li class="layui-col-md3 layui-col-xs6">
                                    <a href="javascript:;" class="x-admin-backlog-body">
                                        <h3>总共币数量DYX</h3>
                                        <p><cite><?=$data20[0]['total']*2?></cite></p>
                                    </a>
                                </li>
                                <li class="layui-col-md3 layui-col-xs6">
                                    <a href="javascript:;" class="x-admin-backlog-body">
                                        <h3>已经提现数量DYX</h3>
                                        <p><cite><?=$data20[0]['wx']?></cite></p>
                                    </a>
                                </li>
                                <li class="layui-col-md3 layui-col-xs6">
                                    <a href="javascript:;" class="x-admin-backlog-body">
                                        <h3>尚未提现数量DYX</h3>
                                        <p><cite><?=$data20[0]['ywx']?></cite></p>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>