<!DOCTYPE html>
<html class="x-admin-sm">
    
    <head>
        <meta charset="UTF-8">
        <title>用户列表</title>
        <meta name="renderer" content="webkit">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta name="viewport" content="width=device-width,user-scalable=yes, minimum-scale=0.4, initial-scale=0.8,target-densitydpi=low-dpi" />
        <link rel="stylesheet" href="/public/css/font.css">
        <link rel="stylesheet" href="/public/css/xadmin.css">
        <script type="text/javascript" src="/public/js/jquery.min.js"></script>
        <script src="/public/lib/layui/layui.js" charset="utf-8"></script>
        <script type="text/javascript" src="/public/js/xadmin.js"></script>
    </head>
    
    <body>
        <div class="x-nav">
            <span class="layui-breadcrumb">
                <a href="">首页</a>
                <a href="">用户管理</a>
                <a><cite>用户列表</cite></a>
            </span>
            <a class="layui-btn layui-btn-small" style="line-height:1.6em;margin-top:3px;float:right" onclick="location.reload()" title="刷新">
                <i class="layui-icon layui-icon-refresh" style="line-height:30px"></i>
            </a>
        </div>
        <div class="layui-fluid">
            <div class="layui-row layui-col-space15">

                <div class="layui-col-md12">

                    <div class="layui-card">
                        <div class="layui-card-header">
                            <button class="layui-btn layui-btn-danger" onclick="delAll()"><i class="layui-icon"></i>批量删除</button>
                            <button class="layui-btn" onclick="xadmin.open('添加用户','#',800,600)"><i class="layui-icon"></i>添加</button>
                            <form action="/admin/usersearch" method="post" style="float: right;">
                                <input type="search" class="layui-input" name="search" placeholder="请输入用户手机号" value="" style="display: inline-block;width: 200px;}">
                                <input type="submit" class="layui-btn" name="username" value="搜索">
                            </form>
                        </div>
                        <div class="layui-card-body ">
                            <table class="layui-table layui-form">
                                <thead>
                                <tr>
                                    <th><input type="checkbox" name="" lay-skin="primary"></th>
                                    <th>用户ID</th>
                                    <th>用户名称</th>
                                    <!--<th>链上地址</th>-->
                                    <th>注册时间</th>
                                    <th>电话</th>
                                    <th>dyx总数量</th>
                                    <th>dyx可用余额</th>
                                    <th>dyx冻结余额</th>
                                    <th>usdt总数量</th>
                                    <th>usdt可用余额</th>
                                    <th>usdt冻结余额</th>
                                    <th>XYT总数量</th>
                                    <th>XYT可用余额</th>
                                    <th>XYT冻结余额</th>
                                    <th>BTC余额</th>
                                    <th>等级</th>
                                </tr>
                                </thead>
                                <tbody>
                                <?php foreach ($arrdata as $k=>$v): ?>
                                    <tr>
                                        <td><input type="checkbox" name="id" lay-skin="primary"></td>
                                        <td><?=$v['id']?></td>
                                        <td><?=$v['username']?></td>
                                        <!--<td><a href="https://etherscan.io/token/0xe4412afb082b51b185acf2b421842465eac96103?a=<?/*=$v['token_address']*/?>" target="_blank" style="color: blue;">链上地址</a></td>-->
                                        <td><?=date("Y-m-d H:i:s",$v['create_time'])?></td>
                                        <td><?=$v['tel']?></td>
                                        <td><?=$v['token_num']?></td>
                                        <td><?=$v['token_available_balance']?></td>
                                        <td><?=$v['token_freeze_balance']?></td>
                                        <td><?=$v['usdt_num']?></td>
                                        <td><?=$v['usdt_available_balance']?></td>
                                        <td><?=$v['usdt_freeze_balance']?></td>
                                        <td><?=$v['xyt_num']?></td>
                                        <td><?=$v['xyt_available_balance']?></td>
                                        <td><?=$v['xyt_freeze_balance']?></td>
                                        <td><?=$v['btc_num']?></td>
                                        <td style="width: 100px;">
                                            <select name="" lay-filter="nameSelect" lay-verify="required" data-id="<?=$v['id']?>" style="width: 100px;">
                                                <option value="1" <?php if($v['level'] == 1){ echo 'selected';} ?>>会员用户</option>
                                                <option value="2" <?php if($v['level'] == 2){ echo 'selected';} ?>>群主</option>
                                            </select>
                                        </td>
                                    </tr>
                                <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                        <div class="layui-card-body ">
                            <?=$showstr?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>

    <script>
        layui.use(['laydate', 'form'], function() {
            var laydate = layui.laydate;
            var form = layui.form;

            //执行一个laydate实例
            laydate.render({
                elem: '#start' //指定元素
            });

            //执行一个laydate实例
            laydate.render({
                elem: '#end' //指定元素
            });

            form.on('select(nameSelect)', function(data){


                var uid = data.elem.dataset.id;
                var s_text = data.value;
                console.log(uid)
                $.post("/admin/ajaxuser",{data:s_text,user:uid},function(msg){
                    layer.msg(msg.message)
                },"json");
                form.render('select');
            });

        });

        /*用户-停用*/
        function member_stop(obj, id) {
            layer.confirm('确认要停用吗？',
            function(index) {

                if ($(obj).attr('title') == '启用') {

                    //发异步把用户状态进行更改
                    $(obj).attr('title', '停用');
                    $(obj).find('i').html('&#xe62f;');

                    $(obj).parents("tr").find(".td-status").find('span').addClass('layui-btn-disabled').html('已停用');
                    layer.msg('已停用!', {
                        icon: 5,
                        time: 1000
                    });

                } else {
                    $(obj).attr('title', '启用');
                    $(obj).find('i').html('&#xe601;');

                    $(obj).parents("tr").find(".td-status").find('span').removeClass('layui-btn-disabled').html('已启用');
                    layer.msg('已启用!', {
                        icon: 5,
                        time: 1000
                    });
                }

            });
        }

        /*用户-删除*/
        function member_del(obj, id) {
            layer.confirm('确认要删除吗？',
            function(index) {
                //发异步删除数据
                $(obj).parents("tr").remove();
                layer.msg('已删除!', {
                    icon: 1,
                    time: 1000
                });
            });
        }

        function delAll(argument) {

            var data = tableCheck.getData();

            layer.confirm('确认要删除吗？' + data,
            function(index) {
                //捉到所有被选中的，发异步进行删除
                layer.msg('删除成功', {
                    icon: 1
                });
                $(".layui-form-checked").not('.header').parents('tr').remove();
            });
        }







    </script>

</html>