<!DOCTYPE html>
<html class="x-admin-sm">
    
    <head>
        <meta charset="UTF-8">
        <title>提现记录</title>
        <meta name="renderer" content="webkit">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta name="viewport" content="width=device-width,user-scalable=yes, minimum-scale=0.4, initial-scale=0.8,target-densitydpi=low-dpi" />
        <link rel="stylesheet" href="/public/css/font.css">
        <link rel="stylesheet" href="/public/css/xadmin.css">
        <script src="/public/lib/layui/layui.js" charset="utf-8"></script>
        <script type="text/javascript" src="/public/js/xadmin.js"></script>
        <script type="text/javascript" src="/public/js/layer.js" charset="utf-8"></script>
    </head>
    
    <body>
        <div class="x-nav">
            <span class="layui-breadcrumb">
                <a href="">首页</a>
                <a href="">演示</a>
                <a>
                    <cite>提现记录</cite></a>
            </span>
            <a class="layui-btn layui-btn-small" style="line-height:1.6em;margin-top:3px;float:right" onclick="location.reload()" title="刷新">
                <i class="layui-icon layui-icon-refresh" style="line-height:30px"></i>
            </a>
        </div>
        <div class="layui-fluid">
            <div class="layui-row layui-col-space15">

                <div class="layui-col-md12">

                    <div class="layui-card">
                        <div class="layui-card-header">
                            <button class="layui-btn layui-btn-danger" onclick="delAll()"><i class="layui-icon"></i>批量删除</button>
                            <button class="layui-btn" onclick="xadmin.open('添加用户','./order-add.html',800,600)"><i class="layui-icon"></i>添加</button>
                            <?php $pageexecl = empty($_GET['page'])?1:$_GET['page'];?>
                            <button class="layui-btn" onclick="window.location.href='/admin/excel?tag=1&type=withdraw&page=<?=$pageexecl?>&showpage=<?=$showpage?>'">导出Excel</button>
                            <button class="layui-btn" onclick="window.location.href='/admin/excel?tag=2&type=withdraw&page=<?=$pageexecl?>&showpage=<?=$showpage?>'">分页导出Excel</button>
                        </div>
                        <div class="layui-card-body ">
                            <table class="layui-table layui-form">
                                <thead>
                                <tr>
                                    <th>排序ID</th>
                                    <th>账号</th>
                                    <th>币种</th>
                                    <th>提现地址</th>
                                    <th>订单</th>
                                    <th>金额</th>
                                    <th>申请状态</th>
                                    <th>处理方式</th>
                                    <th>手动操作</th>
                                    <th>提现时间</th>
                                    <th>提现状态</th>
                                    <th>24小时退款操作</th>
                                </tr>
                                </thead>
                                <tbody>
                                <?php foreach ($arrdata as $k=>$v): ?>
                                    <tr>
                                        <td><?=$v['id']?></td>
                                        <td><?=user_id_name($v['u_id'])?></td>
                                        <?php
                                        $type = "";
                                        switch ($v['currency']){
                                            case 1:$type = "DYX";break;
                                            case 2:$type = "USDT";break;
                                            case 3:$type = "XYT";break;
                                            case 4:$type = "BTC";break;
                                            case 5:$type = "分红股";break;
                                            default:$type = "币种不存在";break;
                                        }
                                        ?>
                                        <th><?=$type?></th>
                                        <th><?=$v['address']?></th>
                                        <th><?=$v['order_no']?></th>
                                        <th><?=$v['token_num']?></th>
                                        <td><?=$v['build_status'] == 1?"<span style='color:green;'>申请成功</span>":"<span style='color:red;'>申请失败</span>"?></td>
                                        <td><?=$v['auto_address'] == 1?"<span style='color:red;'>手动处理</span>":"<span style='color:green;'>自动处理</span>"?></td>
                                        <?php if($v['auto_address'] == 1 && $v['build_status'] == 1 && $v['status'] == 0): ?>
                                            <td class="td-manage">
                                                <a title="通过" onclick="send('<?=$type?>','<?=$v['order_no']?>')" href="javascript:void(0);" class="layui-btn layui-btn-xs">通过</a>
                                                <a title="不通过" onclick="senddel('<?=$v['currency']?>','<?=$v['order_no']?>')" href="javascript:void(0);" class="layui-btn layui-btn-xs layui-btn-warm">不通过</a>
                                            </td>
                                        <?php else: ?>
                                            <td class="td-manage">
                                                &nbsp;
                                            </td>
                                        <?php endif; ?>
                                        <th><?=date("Y-m-d H:i:s",$v['create_time'])?></th>
                                        <td>
                                            <?php if($v['status'] == 1): ?>
                                                <span style='color:green;'>已支付</span>
                                            <?php elseif($v['status'] == 0): ?>
                                                <span style='color:red;'>未支付</span>
                                            <?php elseif($v['status'] == 3):  ?>
                                                <span style='color:red;'>等待手续费</span>
                                            <?php else: ?>
                                                <span style='color:blue;'>已退款</span>
                                            <?php endif; ?>
                                        </td>
                                        <td>
                                            <?php
                                            $time1 = time();
                                            $time2 = $v['create_time'];
                                            $timey = 60*60*24;
                                            $timex = $time1 - $time2;
                                            ?>                       
                                            <?php if($v['build_status'] == 1 && $v['status'] == 0 && $timex > $timey): ?>
                                            <a title="退款" onclick="sendout('<?=$v['u_id']?>','<?=$v['order_no']?>','<?=$v['currency']?>')" href="javascript:void(0);" class="layui-btn layui-btn-xs">退款</a>
                                            <?php elseif($v['build_status'] == 1 && $v['status'] == 3 && $timex > $timey):?>
                                                <a title="退款" onclick="sendout('<?=$v['u_id']?>','<?=$v['order_no']?>','<?=$v['currency']?>')" href="javascript:void(0);" class="layui-btn layui-btn-xs">退款</a>
                                            <?php endif; ?>
                                    </tr>
                                <?php endforeach; ?>
                                </tbody>
                                </tbody>
                            </table>
                        </div>
                        <div class="layui-card-body ">
                            <?=$showstr?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
    <script>
    function senddel(type,order_no) {
       $.post("/ajax/ajaxsenddel",{t:type,od:order_no},function (msg) {
           layer.msg(msg.message);
           setTimeout(function (){
               window.location.href = location.href
           },300);
       },"json");
    }
    function send(type,order_no) {
        $.post("/ajax/ajaxodsend",{t:type,od:order_no},function (msg) {
            layer.msg(msg.message);
            if(msg.message == '操作成功'){
                setTimeout(function () {
                    window.location.href = location.href
                },300);
            }
        },"json");
    }
    function sendout(uid,order_no,btype) {
        $.post("/ajax/ajaxodsendout",{u:uid,od:order_no,b:btype},function (msg) {
            layer.msg(msg.message);
            setTimeout(function () {
                window.location.href = location.href
            },300);
        },"json");
    }
    </script>

</html>