<!DOCTYPE html>
<html class="x-admin-sm">
<head>
    <meta charset="UTF-8">
    <title>DXY新群主额度审核</title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width,user-scalable=yes, minimum-scale=0.4, initial-scale=0.8,target-densitydpi=low-dpi" />
    <link rel="stylesheet" href="/public/css/font.css">
    <link rel="stylesheet" href="/public/css/xadmin.css">
    <script src="/public/js/jquery.min.js"></script>
    <script src="/public/lib/layui/layui.js" charset="utf-8"></script>
    <script type="text/javascript" src="/public/js/xadmin.js"></script>
</head>

<body>
<div class="x-nav">
            <span class="layui-breadcrumb">
                <a href="">首页</a>
                <a href="">审核管理</a>
                <a><cite>DXY新群主额度审核</cite></a>
            </span>
    <a class="layui-btn layui-btn-small" style="line-height:1.6em;margin-top:3px;float:right" onclick="location.reload()" title="刷新">
        <i class="layui-icon layui-icon-refresh" style="line-height:30px"></i>
    </a>
</div>
<div class="layui-fluid">
    <div class="layui-row layui-col-space15">

        <div class="layui-col-md12">

            <div class="layui-card">
                <div class="layui-card-header">
                    <span style="color:#1E9FFF;">总共申请认购群主额度：<?=$num+6?>人</span>&nbsp;
                    <span style="color:#5FB878;">审核通过：<?=$num-$len?>人</span>&nbsp;
                    <span style="color:#FF5722;">待审核：<?=$len?>人</span>
                    <span>直接认购的6人</span>
                </div>
                <div class="layui-card-body ">
                    <table class="layui-table layui-form">
                        <thead>
                        <tr>
                            <th>用户ID</th>
                            <th>申请时间</th>
                            <th>操作</th>
                        </thead>
                        <tbody>
                        <?php foreach($arrdata as $k=>$v): ?>
                        <tr>
                            <td><?=user_id_name($v['u_id'])?></td>
                            <td><?=date("Y-m-d H:i:s",$v['create_time'])?></td>
                            <td class="td-manage">
                                <a title="通过" href="javascript:void(0);" class="layui-btn layui-btn-xs" onclick="send(<?=$v['id']?>,<?=$v['u_id']?>)">通过</a>
                                <a title="不通过" href="javascript:void(0);" class="layui-btn layui-btn-xs layui-btn-danger" onclick="senddel(<?=$v['id']?>,<?=$v['u_id']?>)">不通过</a>
                            </td>
                        </tr>
                        <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
                <div class="layui-card-body ">
                    <?=$showstr?>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
   function send(tag,uid){
       $.post("/ajax/dyxgroup",{id:tag,uid:uid},function(msg){
           layer.msg(msg.msg);
           setTimeout(function () {
               window.location.href = location.href
           },1000);
       },"json");
   }
   function senddel(tag,uid){
       $.post("/ajax/dyxgroupdel",{id:tag,uid:uid},function(msg){
           layer.msg(msg.msg);
           setTimeout(function () {
               window.location.href = location.href
           },1000);
       },"json");
   }
</script>

</body>
</html>