<!DOCTYPE html>
<html class="x-admin-sm">
    
    <head>
        <meta charset="UTF-8">
        <title>DXY霸屏会员空投奖励</title>
        <meta name="renderer" content="webkit">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta name="viewport" content="width=device-width,user-scalable=yes, minimum-scale=0.4, initial-scale=0.8,target-densitydpi=low-dpi" />
        <link rel="stylesheet" href="/public/css/font.css">
        <link rel="stylesheet" href="/public/css/xadmin.css">
        <script type="text/javascript" src="/public/js/jquery.min.js"></script>
        <script type="text/javascript" src="/public/js/layer.js" charset="utf-8"></script>
        <script type="text/javascript" src="/public/lib/layui/layui.js" charset="utf-8"></script>
        <script type="text/javascript" src="/public/js/xadmin.js"></script>
        <style>
            .x-admin-sm .layui-input, .x-admin-sm .layui-select, .x-admin-sm .layui-textarea {
                height: 41px;
            }
        </style>
    </head>
    
    <body>
        <div class="x-nav">
            <span class="layui-breadcrumb">
                <a href="">首页</a>
                <a href="">演示</a>
                <a>
                    <cite>DXY霸屏会员空投奖励</cite></a>
            </span>
            <a class="layui-btn layui-btn-small" style="line-height:1.6em;margin-top:3px;float:right" onclick="location.reload()" title="刷新">
                <i class="layui-icon layui-icon-refresh" style="line-height:30px"></i>
            </a>
        </div>
        <div class="layui-fluid">
            <div class="layui-row layui-col-space15">
                <div class="layui-col-md12">
                    <div class="layui-card">
                        <div class="layui-card-header">
                            <div class="layui-fluid">
                                <div class="layui-row">
                        <div class="layui-form-item">
                            <label for="L_repass" class="layui-form-label">
                                空投奖励
                            </label>
                            <div class="layui-input-inline">
                                <input type="tel" id="tel" name="tel" placeholder="输入手机号" class="layui-input"  value="">
                            </div>
                            <div class="layui-input-inline">
                                <input type="text" id="price" name="price" placeholder="请输入金额" class="layui-input"  value="">
                            </div>
                            <button type="submit" id="btn"  class="layui-btn" style="height: 42px;padding: 0 20px;">提交</button>
                        </div>

                            </div>
                            </div>
                            <div>

                    </div>
                </div>
                <br><br>
                <div class="layui-col-md12">
                    <div class="layui-card">
                        <div class="layui-card-body ">
                            <table class="layui-table layui-form">
                                <thead>
                                    <tr>
                                        <th>排序</th>
                                        <th>管理员</th>
                                        <th>账号</th>
                                        <th>类型</th>
                                        <th>金额</th>
                                        <th>IP</th>
                                        <th>时间</th>
                                </thead>
                                <tbody>
                                    <?php foreach ($arrdata as $k=>$v): ?>
                                    <tr>
                                        <td><?=$v['id']?></td>
                                        <td><?=$v['admin']?></td>
                                        <td><?=$v['tel']?></td>
                                        <td><?=$v['type']?></td>
                                        <td><?=$v['price']?>DYX</td>
                                        <td><?=$v['ip']?></td>
                                        <td><?=date("Y-m-d H:i:s",$v['create_time'])?></td>
                                    </tr>
                                    <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                        <div class="layui-card-body ">
                            <?=$showstr?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
    <script>
        layui.use(['laydate', 'form'],
        function() {
            var laydate = layui.laydate;

            //执行一个laydate实例
            laydate.render({
                elem: '#start' //指定元素
            });

            //执行一个laydate实例
            laydate.render({
                elem: '#end' //指定元素
            });
        });

    $(function () {
        $("#btn").click(function(){
            var price = parseFloat($("#price").val()).toFixed(3);
            var tel = $("#tel").val();
            var exp = /^1[3456789]\d{9}$/;
            var bool = exp.test(tel);
            if(!bool){
                layer.msg("请输入有效的手机号");
                return false;
            }

            if(isNaN(price)){
                layer.msg("请输入有效的金额");
                return false;
            }

            $.post("/operate/dyxkt",{t:tel,p:price},function(msg){
                layer.alert(msg.message);
                if(msg.code == 1){
                    setTimeout(function () {
                        window.location.href = location.href
                    },300);
                }
            },"json");
            console.log(price);


        });
    });


    </script>

</html>