<!DOCTYPE html>
<html class="x-admin-sm">
<head>
    <meta charset="UTF-8">
    <title>DXY霸屏任务发布</title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width,user-scalable=yes, minimum-scale=0.4, initial-scale=0.8,target-densitydpi=low-dpi" />
    <link rel="stylesheet" href="/public/css/font.css">
    <link rel="stylesheet" href="/public/css/xadmin.css">
    <link rel="stylesheet" href="/public/css/xadmin_pascreen.css">
    <script type="text/javascript" src="/public/js/jquery.min.js"></script>
    <script src="/public/lib/layui/layui.js" charset="utf-8"></script>
    <script type="text/javascript" src="/public/js/xadmin.js"></script>
</head>

<body>
<div class="x-nav">
    <span class="layui-breadcrumb">
        <a href="">首页</a>
        <a href="">活动管理</a>
        <a><cite>DXY霸屏任务发布</cite></a>
    </span>
    <a class="layui-btn layui-btn-small" style="line-height:1.6em;margin-top:3px;float:right" onclick="location.reload()" title="刷新"><i class="layui-icon layui-icon-refresh" style="line-height:30px"></i></a>
</div>
<div class="layui-fluid">
    <div class="layui-row layui-col-space15">
        <div class="layui-col-sm6 layui-col-md6">
            <div class="layui-card">
                <div class="layui-card-header layui-h">朋友圈图文1</div>
                <div class="layui-card-body">
                    <div style="overflow: hidden;">
                        <span style="float: left;font-size: 18px;padding: 4px 10px;width: 10%;" class="layui-badge layui-bg-cyan layuiadmin-badge">展示</span>
                        <div style="width: 85%;height: 280px;overflow-y: scroll;border: 1px solid #a9a9a9;float: left;margin-left: 2px"><img id="pic1" src="<?=$result['pic1']?>" alt=""></div>
                    </div>
                    <div class="layuiadmin-big-font" style="overflow: hidden;margin: 20px 0;">
                        <span style="float: left;font-size: 18px;padding: 4px 10px;width: 10%;" class="layui-badge layui-bg-cyan layuiadmin-badge">图片</span>
                        <div class="imgone pr">
                            <input type="file" name="file1" accept="image/*" value="" onchange="selectFile(this,event,'pic1')">
                            <div class="upload-btn">
                                <img src="/public/images/website/upload-btn.png" width="70" height="70" alt=""  >
                                <p>上传截图</p>
                            </div>
                        </div>
                    </div>

                    <div class="layuiadmin-big-font" style="overflow: hidden;margin: 20px 0;">
                        <p style="overflow: hidden">
                            <span style="float: left;font-size: 18px;padding: 4px 10px;width: 10%;" class="layui-badge layui-bg-cyan layuiadmin-badge">文案</span>
                            <textarea id="pic1text" name="text1" cols="65" rows="5"><?=$result['text1']?></textarea>
                        </p>
                    </div>
                    <div class="layuiadmin-big-font" style="overflow: hidden;margin: 20px 0;text-align: center;">
                        <p>
                            <input type="hidden" id="pic1hidden" name="pic1" value="<?=$result['pic1']?>">
                            <?php if($c == 1): ?>
                                <?php if($a == 1): ?>
                                    <span style="font-size: 18px;padding: 4px 10px;background: #009688 !important;" class="layui-badge layui-bg-cyan layuiadmin-badge"  onclick="">今日已更新图文，请明日再来</span>
                                <?php else: ?>
                                    <span style="font-size: 18px;padding: 4px 10px;background: #009688 !important;" class="layui-badge layui-bg-cyan layuiadmin-badge"  onclick="send('pic1',this)">保存</span>
                                <?php endif; ?>
                            <?php else: ?>
                                <span style="font-size: 18px;padding: 4px 10px;background: #009688 !important;" class="layui-badge layui-bg-cyan layuiadmin-badge"  onclick="send('pic1',this)">保存</span>
                            <?php endif; ?>

                        </p>
                    </div>
                </div>
            </div>
        </div>
        <div class="layui-col-sm6 layui-col-md6">
            <div class="layui-card">
                <div class="layui-card-header layui-h">朋友圈图文2</div>
                <div class="layui-card-body">
                    <div style="overflow: hidden;">
                        <span style="float: left;font-size: 18px;padding: 4px 10px;width: 10%;" class="layui-badge layui-bg-cyan layuiadmin-badge">展示</span>
                        <div style="width: 85%;height: 280px;overflow-y: scroll;border: 1px solid #a9a9a9;float: left;margin-left: 2px"><img id="pic2" src="<?=$result['pic2']?>" alt=""></div>
                    </div>
                    <div class="layuiadmin-big-font" style="overflow: hidden;margin: 20px 0;">
                        <span style="float: left;font-size: 18px;padding: 4px 10px;width: 10%;" class="layui-badge layui-bg-cyan layuiadmin-badge">图片</span>
                        <div class="imgone pr">
                            <input type="file" name="file2" accept="image/*" value="" onchange="selectFile(this,event,'pic2')">
                            <div class="upload-btn">
                                <img src="/public/images/website/upload-btn.png" width="70" height="70" alt=""  >
                                <p>上传截图</p>
                            </div>
                        </div>
                    </div>

                    <div class="layuiadmin-big-font" style="overflow: hidden;margin: 20px 0;">
                        <p style="overflow: hidden">
                            <span style="float: left;font-size: 18px;padding: 4px 10px;width: 10%;" class="layui-badge layui-bg-cyan layuiadmin-badge">文案</span>
                            <textarea id="pic2text" name="text2" cols="65" rows="5"><?=$result['text2']?></textarea>
                        </p>
                    </div>
                    <div class="layuiadmin-big-font" style="overflow: hidden;margin: 20px 0;text-align: center;">
                        <p>
                            <input type="hidden" id="pic2hidden" name="pic2" value="<?=$result['pic2']?>">
                            <?php if($d == 1): ?>
                                <?php if($b == 1): ?>
                                    <span style="font-size: 18px;padding: 4px 10px;background: #009688 !important;" class="layui-badge layui-bg-cyan layuiadmin-badge"  onclick="">今日已更新图文，请明日再来</span>
                                <?php else: ?>
                                    <span style="font-size: 18px;padding: 4px 10px;background: #009688 !important;" class="layui-badge layui-bg-cyan layuiadmin-badge"  onclick="send('pic2',this)">保存</span>
                                <?php endif; ?>
                            <?php else: ?>
                                <span style="font-size: 18px;padding: 4px 10px;background: #009688 !important;" class="layui-badge layui-bg-cyan layuiadmin-badge"  onclick="send('pic2',this)">保存</span>
                            <?php endif; ?>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
<script>

    //读取图片和提交后端
    let form = new FormData();//通过HTML表单创建FormData对象
    let upload;
    let inputhidden;
    function selectFile(tag,e,type){
        var that = $(tag);
        let files = e.currentTarget.files;
        if(files.length == 0){
            return;
        }
        let file = files[0];
        //把上传的图片显示出来
        let reader = new FileReader();
        // 将文件以Data URL形式进行读入页面
        reader.readAsBinaryString(file);
        /* reader.onload = function(f){
         //var index = $(tag).index();
         upload = $(tag).next("div");
         let src = "data:" + file.type + ";base64," + window.btoa(this.result);
         };*/
        form.append('file',file);
        //提交
        let httpRequest;
        //ie7+ 主流浏览器
        if(window.XMLHttpRequest){
            //alert("ie7+ 主流浏览器");
            httpRequest = new XMLHttpRequest();
        }else if(window.ActiveXObject){
            //alert("ie7-");
            httpRequest = new ActiveXObject("Microsoft.XMLHTTP");
        }else{
            alert("主流浏览器");
        }
        httpRequest.open("post","/ajax/upload",true);
        //httpRequest.setRequestHeader("Content-Type","application/x-www-form-urlencoded;charset=utf-8");
        httpRequest.send(form);
        httpRequest.onreadystatechange =()=> {
            // 信息已经返回，可以开始处理
            if (httpRequest.readyState == 4) {
                // 页面正常，可以开始处理信息
                if (httpRequest.status == 200) {
                    let resdata = eval("("+httpRequest.responseText+")");
                    if(resdata.msg == "ok"){
                        $("#"+type).attr("src","/public"+resdata.data);
                        $("#"+type+"hidden").val("/public"+resdata.data);
//                        upload = $(tag).next("div");
//                        upload.html("<img class='book-pic' src ='/public"+resdata.data+"' style='width: 100%' />");
//                        $("#"+type).val(resdata.data);
                    }
                }
            }
        }
    }

    function send(type,tag) {
        var hiddenurl = $("#"+type+"hidden").val();
        if(hiddenurl == ""){
          layer.msg("缺少图片资源");
          return false;
        }
        var textinfo = $("#"+type+"text").val();
        if(textinfo == ""){
            layer.msg("缺少文案资源");
            return false;
        }
       $.post("/admin/dyxrelease",{p:hiddenurl,t:textinfo,type:type},function(msg){
          if(msg.code == 1){
              layer.msg("更新成功");
              tag.innerHTML = "今日更新图文-篇，请明日再来";
              tag.onclick = null;
          }else{
              layer.msg("更新失败");
          }
       },"json");
    }
</script>

</html>


600216
