<!doctype html>
<html  class="x-admin-sm">
<head>
	<meta charset="UTF-8">
	<title>后台登录-X-admin2.2</title>
	<meta name="renderer" content="webkit|ie-comp|ie-stand">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width,user-scalable=yes, minimum-scale=0.4, initial-scale=0.8,target-densitydpi=low-dpi" />
    <meta http-equiv="Cache-Control" content="no-siteapp" />
    <link rel="stylesheet" href="/public/css/font.css">
    <link rel="stylesheet" href="/public/css/login.css">
	  <link rel="stylesheet" href="/public/css/xadmin.css">
    <script type="text/javascript" src="https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js"></script>
    <script src="/public/lib/layui/layui.js" charset="utf-8"></script>
</head>
<body class="login-bg">
    
    <div class="login layui-anim layui-anim-up">
        <div class="message">xcoinpay-管理登录</div>
        <div id="darkbannerwrap"></div>
        
        <form action="/login/index" method="post" class="layui-form" >
            <input type="text" name="user" placeholder="用户名"   lay-verify="required" class="layui-input" value="" >
            <hr class="hr15">
            <input type="password" name="pass" lay-verify="required" placeholder="密码"  class="layui-input" value="">
            <hr class="hr15">
            <input type="submit" value="登录" lay-submit lay-filter="login" style="width:100%;" >
            <hr class="hr20" >
        </form>
    </div>
    <!-- 底部结束 -->
</body>
</html>